<?php
/**
 * HealthApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  KeyNetra\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KeyNetra
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace KeyNetra\Client\Test\Api;

use \KeyNetra\Client\Configuration;
use \KeyNetra\Client\ApiException;
use \KeyNetra\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * HealthApiTest Class Doc Comment
 *
 * @category Class
 * @package  KeyNetra\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HealthApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for healthHealthGet
     *
     * Health.
     *
     */
    public function testHealthHealthGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for livenessHealthLiveGet
     *
     * Liveness.
     *
     */
    public function testLivenessHealthLiveGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readinessHealthReadyGet
     *
     * Readiness.
     *
     */
    public function testReadinessHealthReadyGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
