# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.api.access_api import AccessApi


class TestAccessApi(unittest.TestCase):
    """AccessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccessApi()

    def tearDown(self) -> None:
        pass

    def test_check_access_batch_check_access_batch_post(self) -> None:
        """Test case for check_access_batch_check_access_batch_post

        Check Access Batch
        """
        pass

    def test_check_access_check_access_post(self) -> None:
        """Test case for check_access_check_access_post

        Check Access
        """
        pass

    def test_simulate_simulate_post(self) -> None:
        """Test case for simulate_simulate_post

        Simulate
        """
        pass


if __name__ == '__main__':
    unittest.main()
