# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.playground_evaluate_request import PlaygroundEvaluateRequest

class TestPlaygroundEvaluateRequest(unittest.TestCase):
    """PlaygroundEvaluateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlaygroundEvaluateRequest:
        """Test PlaygroundEvaluateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlaygroundEvaluateRequest`
        """
        model = PlaygroundEvaluateRequest()
        if include_optional:
            return PlaygroundEvaluateRequest(
                policies = [
                    keynetra_client.models.playground_policy.PlaygroundPolicy(
                        action = '', 
                        effect = 'allow', 
                        priority = 56, 
                        policy_id = '', 
                        conditions = { }, )
                    ],
                input = keynetra_client.models.playground_input.PlaygroundInput(
                    user = { }, 
                    resource = { }, 
                    action = '', 
                    context = { }, )
            )
        else:
            return PlaygroundEvaluateRequest(
                policies = [
                    keynetra_client.models.playground_policy.PlaygroundPolicy(
                        action = '', 
                        effect = 'allow', 
                        priority = 56, 
                        policy_id = '', 
                        conditions = { }, )
                    ],
                input = keynetra_client.models.playground_input.PlaygroundInput(
                    user = { }, 
                    resource = { }, 
                    action = '', 
                    context = { }, ),
        )
        """

    def testPlaygroundEvaluateRequest(self):
        """Test PlaygroundEvaluateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
