# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.success_response_list_dict_str_str import SuccessResponseListDictStrStr

class TestSuccessResponseListDictStrStr(unittest.TestCase):
    """SuccessResponseListDictStrStr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessResponseListDictStrStr:
        """Test SuccessResponseListDictStrStr
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessResponseListDictStrStr`
        """
        model = SuccessResponseListDictStrStr()
        if include_optional:
            return SuccessResponseListDictStrStr(
                data = [
                    {
                        'key' : ''
                        }
                    ],
                meta = keynetra_client.models.meta_body.MetaBody(
                    request_id = '', 
                    limit = 56, 
                    next_cursor = '', 
                    extra = { }, ),
                error = None
            )
        else:
            return SuccessResponseListDictStrStr(
                data = [
                    {
                        'key' : ''
                        }
                    ],
        )
        """

    def testSuccessResponseListDictStrStr(self):
        """Test SuccessResponseListDictStrStr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
