# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.audit_record_out import AuditRecordOut

class TestAuditRecordOut(unittest.TestCase):
    """AuditRecordOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuditRecordOut:
        """Test AuditRecordOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuditRecordOut`
        """
        model = AuditRecordOut()
        if include_optional:
            return AuditRecordOut(
                id = 56,
                principal_type = '',
                principal_id = '',
                correlation_id = '',
                user = { },
                action = '',
                resource = { },
                decision = '',
                matched_policies = [
                    null
                    ],
                reason = '',
                evaluated_rules = [
                    null
                    ],
                failed_conditions = [
                    null
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AuditRecordOut(
                id = 56,
                principal_type = '',
                principal_id = '',
                user = { },
                action = '',
                resource = { },
                decision = '',
                matched_policies = [
                    null
                    ],
                evaluated_rules = [
                    null
                    ],
                failed_conditions = [
                    null
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testAuditRecordOut(self):
        """Test AuditRecordOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
