# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.api.dev_api import DevApi


class TestDevApi(unittest.TestCase):
    """DevApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DevApi()

    def tearDown(self) -> None:
        pass

    def test_get_sample_data_dev_sample_data_get(self) -> None:
        """Test case for get_sample_data_dev_sample_data_get

        Get Sample Data
        """
        pass

    def test_seed_sample_data_dev_sample_data_seed_post(self) -> None:
        """Test case for seed_sample_data_dev_sample_data_seed_post

        Seed Sample Data
        """
        pass


if __name__ == '__main__':
    unittest.main()
