# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.success_response_dict_str_int import SuccessResponseDictStrInt

class TestSuccessResponseDictStrInt(unittest.TestCase):
    """SuccessResponseDictStrInt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessResponseDictStrInt:
        """Test SuccessResponseDictStrInt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessResponseDictStrInt`
        """
        model = SuccessResponseDictStrInt()
        if include_optional:
            return SuccessResponseDictStrInt(
                data = {
                    'key' : 56
                    },
                meta = keynetra_client.models.meta_body.MetaBody(
                    request_id = '', 
                    limit = 56, 
                    next_cursor = '', 
                    extra = { }, ),
                error = None
            )
        else:
            return SuccessResponseDictStrInt(
                data = {
                    'key' : 56
                    },
        )
        """

    def testSuccessResponseDictStrInt(self):
        """Test SuccessResponseDictStrInt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
