# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.api.health_api import HealthApi


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthApi()

    def tearDown(self) -> None:
        pass

    def test_health_health_get(self) -> None:
        """Test case for health_health_get

        Health
        """
        pass

    def test_liveness_health_live_get(self) -> None:
        """Test case for liveness_health_live_get

        Liveness
        """
        pass

    def test_readiness_health_ready_get(self) -> None:
        """Test case for readiness_health_ready_get

        Readiness
        """
        pass


if __name__ == '__main__':
    unittest.main()
