# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.acl_create import ACLCreate

class TestACLCreate(unittest.TestCase):
    """ACLCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ACLCreate:
        """Test ACLCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ACLCreate`
        """
        model = ACLCreate()
        if include_optional:
            return ACLCreate(
                subject_type = '',
                subject_id = '',
                resource_type = '',
                resource_id = '',
                action = '',
                effect = ''
            )
        else:
            return ACLCreate(
                subject_type = '',
                subject_id = '',
                resource_type = '',
                resource_id = '',
                action = '',
                effect = '',
        )
        """

    def testACLCreate(self):
        """Test ACLCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
