# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_admin_login_admin_login_post(self) -> None:
        """Test case for admin_login_admin_login_post

        Admin Login
        """
        pass

    def test_admin_login_admin_login_post_0(self) -> None:
        """Test case for admin_login_admin_login_post_0

        Admin Login
        """
        pass


if __name__ == '__main__':
    unittest.main()
