# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.success_response_acl_out import SuccessResponseACLOut

class TestSuccessResponseACLOut(unittest.TestCase):
    """SuccessResponseACLOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessResponseACLOut:
        """Test SuccessResponseACLOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessResponseACLOut`
        """
        model = SuccessResponseACLOut()
        if include_optional:
            return SuccessResponseACLOut(
                data = keynetra_client.models.acl_out.ACLOut(
                    subject_type = '', 
                    subject_id = '', 
                    resource_type = '', 
                    resource_id = '', 
                    action = '', 
                    effect = '', 
                    id = 56, 
                    tenant_id = 56, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                meta = keynetra_client.models.meta_body.MetaBody(
                    request_id = '', 
                    limit = 56, 
                    next_cursor = '', 
                    extra = { }, ),
                error = None
            )
        else:
            return SuccessResponseACLOut(
                data = keynetra_client.models.acl_out.ACLOut(
                    subject_type = '', 
                    subject_id = '', 
                    resource_type = '', 
                    resource_id = '', 
                    action = '', 
                    effect = '', 
                    id = 56, 
                    tenant_id = 56, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testSuccessResponseACLOut(self):
        """Test SuccessResponseACLOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
