# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.auth_model_out import AuthModelOut

class TestAuthModelOut(unittest.TestCase):
    """AuthModelOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthModelOut:
        """Test AuthModelOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthModelOut`
        """
        model = AuthModelOut()
        if include_optional:
            return AuthModelOut(
                id = 56,
                tenant_id = 56,
                var_schema = '',
                parsed = { },
                compiled = { }
            )
        else:
            return AuthModelOut(
                id = 56,
                tenant_id = 56,
                var_schema = '',
                parsed = { },
                compiled = { },
        )
        """

    def testAuthModelOut(self):
        """Test AuthModelOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
