# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.policy_out import PolicyOut

class TestPolicyOut(unittest.TestCase):
    """PolicyOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyOut:
        """Test PolicyOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyOut`
        """
        model = PolicyOut()
        if include_optional:
            return PolicyOut(
                id = 56,
                action = '',
                effect = '',
                priority = 56,
                state = 'active',
                conditions = { }
            )
        else:
            return PolicyOut(
                id = 56,
                action = '',
                effect = '',
                priority = 56,
                conditions = { },
        )
        """

    def testPolicyOut(self):
        """Test PolicyOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
