# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.success_response_batch_access_response import SuccessResponseBatchAccessResponse

class TestSuccessResponseBatchAccessResponse(unittest.TestCase):
    """SuccessResponseBatchAccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessResponseBatchAccessResponse:
        """Test SuccessResponseBatchAccessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessResponseBatchAccessResponse`
        """
        model = SuccessResponseBatchAccessResponse()
        if include_optional:
            return SuccessResponseBatchAccessResponse(
                data = keynetra_client.models.batch_access_response.BatchAccessResponse(
                    results = [
                        keynetra_client.models.batch_access_result.BatchAccessResult(
                            action = '', 
                            allowed = True, 
                            revision = 56, )
                        ], 
                    revision = 56, ),
                meta = keynetra_client.models.meta_body.MetaBody(
                    request_id = '', 
                    limit = 56, 
                    next_cursor = '', 
                    extra = { }, ),
                error = None
            )
        else:
            return SuccessResponseBatchAccessResponse(
                data = keynetra_client.models.batch_access_response.BatchAccessResponse(
                    results = [
                        keynetra_client.models.batch_access_result.BatchAccessResult(
                            action = '', 
                            allowed = True, 
                            revision = 56, )
                        ], 
                    revision = 56, ),
        )
        """

    def testSuccessResponseBatchAccessResponse(self):
        """Test SuccessResponseBatchAccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
