# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.success_response_permission_out import SuccessResponsePermissionOut

class TestSuccessResponsePermissionOut(unittest.TestCase):
    """SuccessResponsePermissionOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessResponsePermissionOut:
        """Test SuccessResponsePermissionOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessResponsePermissionOut`
        """
        model = SuccessResponsePermissionOut()
        if include_optional:
            return SuccessResponsePermissionOut(
                data = keynetra_client.models.permission_out.PermissionOut(
                    id = 56, 
                    action = '', ),
                meta = keynetra_client.models.meta_body.MetaBody(
                    request_id = '', 
                    limit = 56, 
                    next_cursor = '', 
                    extra = { }, ),
                error = None
            )
        else:
            return SuccessResponsePermissionOut(
                data = keynetra_client.models.permission_out.PermissionOut(
                    id = 56, 
                    action = '', ),
        )
        """

    def testSuccessResponsePermissionOut(self):
        """Test SuccessResponsePermissionOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
