# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.batch_access_response import BatchAccessResponse

class TestBatchAccessResponse(unittest.TestCase):
    """BatchAccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchAccessResponse:
        """Test BatchAccessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchAccessResponse`
        """
        model = BatchAccessResponse()
        if include_optional:
            return BatchAccessResponse(
                results = [
                    keynetra_client.models.batch_access_result.BatchAccessResult(
                        action = '', 
                        allowed = True, 
                        revision = 56, )
                    ],
                revision = 56
            )
        else:
            return BatchAccessResponse(
                results = [
                    keynetra_client.models.batch_access_result.BatchAccessResult(
                        action = '', 
                        allowed = True, 
                        revision = 56, )
                    ],
        )
        """

    def testBatchAccessResponse(self):
        """Test BatchAccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
