# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.access_decision_response import AccessDecisionResponse

class TestAccessDecisionResponse(unittest.TestCase):
    """AccessDecisionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessDecisionResponse:
        """Test AccessDecisionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccessDecisionResponse`
        """
        model = AccessDecisionResponse()
        if include_optional:
            return AccessDecisionResponse(
                allowed = True,
                decision = '',
                matched_policies = [
                    ''
                    ],
                reason = '',
                policy_id = '',
                explain_trace = [
                    { }
                    ],
                revision = 56
            )
        else:
            return AccessDecisionResponse(
                allowed = True,
                decision = '',
        )
        """

    def testAccessDecisionResponse(self):
        """Test AccessDecisionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
