# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.playground_policy import PlaygroundPolicy

class TestPlaygroundPolicy(unittest.TestCase):
    """PlaygroundPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlaygroundPolicy:
        """Test PlaygroundPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlaygroundPolicy`
        """
        model = PlaygroundPolicy()
        if include_optional:
            return PlaygroundPolicy(
                action = '',
                effect = 'allow',
                priority = 56,
                policy_id = '',
                conditions = { }
            )
        else:
            return PlaygroundPolicy(
                action = '',
        )
        """

    def testPlaygroundPolicy(self):
        """Test PlaygroundPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
