# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keynetra_client.models.permission_out import PermissionOut

class TestPermissionOut(unittest.TestCase):
    """PermissionOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PermissionOut:
        """Test PermissionOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PermissionOut`
        """
        model = PermissionOut()
        if include_optional:
            return PermissionOut(
                id = 56,
                action = ''
            )
        else:
            return PermissionOut(
                id = 56,
                action = '',
        )
        """

    def testPermissionOut(self):
        """Test PermissionOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
