=begin
#KeyNetra

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KeyNetra::PlaygroundEvaluateRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KeyNetra::PlaygroundEvaluateRequest do
  #let(:instance) { KeyNetra::PlaygroundEvaluateRequest.new }

  describe 'test an instance of PlaygroundEvaluateRequest' do
    it 'should create an instance of PlaygroundEvaluateRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KeyNetra::PlaygroundEvaluateRequest)
    end
  end

  describe 'test attribute "policies"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "input"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
