=begin
#KeyNetra

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KeyNetra::PolicySimulationRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KeyNetra::PolicySimulationRequest do
  #let(:instance) { KeyNetra::PolicySimulationRequest.new }

  describe 'test an instance of PolicySimulationRequest' do
    it 'should create an instance of PolicySimulationRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KeyNetra::PolicySimulationRequest)
    end
  end

  describe 'test attribute "simulate"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "request"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
