//
// AccessAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AccessAPI {

    /**
     Check Access Batch
     
     - parameter batchAccessRequest: (body)  
     - parameter policySet: (query)  (optional, default to "active")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func checkAccessBatchCheckAccessBatchPost(batchAccessRequest: BatchAccessRequest, policySet: String? = nil, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseBatchAccessResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return checkAccessBatchCheckAccessBatchPostWithRequestBuilder(batchAccessRequest: batchAccessRequest, policySet: policySet).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Check Access Batch
     - POST /check-access-batch
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter batchAccessRequest: (body)  
     - parameter policySet: (query)  (optional, default to "active")
     - returns: RequestBuilder<SuccessResponseBatchAccessResponse> 
     */
    open class func checkAccessBatchCheckAccessBatchPostWithRequestBuilder(batchAccessRequest: BatchAccessRequest, policySet: String? = nil) -> RequestBuilder<SuccessResponseBatchAccessResponse> {
        let localVariablePath = "/check-access-batch"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: batchAccessRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "policy_set": (wrappedValue: policySet?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseBatchAccessResponse>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Check Access
     
     - parameter accessRequest: (body)  
     - parameter policySet: (query)  (optional, default to "active")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func checkAccessCheckAccessPost(accessRequest: AccessRequest, policySet: String? = nil, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseAccessDecisionResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return checkAccessCheckAccessPostWithRequestBuilder(accessRequest: accessRequest, policySet: policySet).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Check Access
     - POST /check-access
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter accessRequest: (body)  
     - parameter policySet: (query)  (optional, default to "active")
     - returns: RequestBuilder<SuccessResponseAccessDecisionResponse> 
     */
    open class func checkAccessCheckAccessPostWithRequestBuilder(accessRequest: AccessRequest, policySet: String? = nil) -> RequestBuilder<SuccessResponseAccessDecisionResponse> {
        let localVariablePath = "/check-access"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: accessRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "policy_set": (wrappedValue: policySet?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseAccessDecisionResponse>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Simulate
     
     - parameter accessRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func simulateSimulatePost(accessRequest: AccessRequest, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseSimulationResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return simulateSimulatePostWithRequestBuilder(accessRequest: accessRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Simulate
     - POST /simulate
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter accessRequest: (body)  
     - returns: RequestBuilder<SuccessResponseSimulationResponse> 
     */
    open class func simulateSimulatePostWithRequestBuilder(accessRequest: AccessRequest) -> RequestBuilder<SuccessResponseSimulationResponse> {
        let localVariablePath = "/simulate"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: accessRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseSimulationResponse>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
