//
// AuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AuthAPI {

    /**
     Admin Login
     
     - parameter adminLoginRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adminLoginAdminLoginPost(adminLoginRequest: AdminLoginRequest, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseAdminLoginResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return adminLoginAdminLoginPostWithRequestBuilder(adminLoginRequest: adminLoginRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Admin Login
     - POST /admin/login
     - parameter adminLoginRequest: (body)  
     - returns: RequestBuilder<SuccessResponseAdminLoginResponse> 
     */
    open class func adminLoginAdminLoginPostWithRequestBuilder(adminLoginRequest: AdminLoginRequest) -> RequestBuilder<SuccessResponseAdminLoginResponse> {
        let localVariablePath = "/admin/login"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: adminLoginRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseAdminLoginResponse>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Admin Login
     
     - parameter adminLoginRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adminLoginAdminLoginPost_0(adminLoginRequest: AdminLoginRequest, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseAdminLoginResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return adminLoginAdminLoginPost_0WithRequestBuilder(adminLoginRequest: adminLoginRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Admin Login
     - POST /admin/login
     - parameter adminLoginRequest: (body)  
     - returns: RequestBuilder<SuccessResponseAdminLoginResponse> 
     */
    open class func adminLoginAdminLoginPost_0WithRequestBuilder(adminLoginRequest: AdminLoginRequest) -> RequestBuilder<SuccessResponseAdminLoginResponse> {
        let localVariablePath = "/admin/login"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: adminLoginRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseAdminLoginResponse>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
