//
// DevAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DevAPI {

    /**
     Get Sample Data
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSampleDataDevSampleDataGet(apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrObject?, _ error: Error?) -> Void)) -> RequestTask {
        return getSampleDataDevSampleDataGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Sample Data
     - GET /dev/sample-data
     - returns: RequestBuilder<SuccessResponseDictStrObject> 
     */
    open class func getSampleDataDevSampleDataGetWithRequestBuilder() -> RequestBuilder<SuccessResponseDictStrObject> {
        let localVariablePath = "/dev/sample-data"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrObject>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Seed Sample Data
     
     - parameter reset: (query) Clear the sample dataset before reseeding it. (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func seedSampleDataDevSampleDataSeedPost(reset: Bool? = nil, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrObject?, _ error: Error?) -> Void)) -> RequestTask {
        return seedSampleDataDevSampleDataSeedPostWithRequestBuilder(reset: reset).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Seed Sample Data
     - POST /dev/sample-data/seed
     - parameter reset: (query) Clear the sample dataset before reseeding it. (optional, default to false)
     - returns: RequestBuilder<SuccessResponseDictStrObject> 
     */
    open class func seedSampleDataDevSampleDataSeedPostWithRequestBuilder(reset: Bool? = nil) -> RequestBuilder<SuccessResponseDictStrObject> {
        let localVariablePath = "/dev/sample-data/seed"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "reset": (wrappedValue: reset?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrObject>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
