//
// HealthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class HealthAPI {

    /**
     Health
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func healthHealthGet(apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrStr?, _ error: Error?) -> Void)) -> RequestTask {
        return healthHealthGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Health
     - GET /health
     - returns: RequestBuilder<SuccessResponseDictStrStr> 
     */
    open class func healthHealthGetWithRequestBuilder() -> RequestBuilder<SuccessResponseDictStrStr> {
        let localVariablePath = "/health"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrStr>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Liveness
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func livenessHealthLiveGet(apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrStr?, _ error: Error?) -> Void)) -> RequestTask {
        return livenessHealthLiveGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Liveness
     - GET /health/live
     - returns: RequestBuilder<SuccessResponseDictStrStr> 
     */
    open class func livenessHealthLiveGetWithRequestBuilder() -> RequestBuilder<SuccessResponseDictStrStr> {
        let localVariablePath = "/health/live"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrStr>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Readiness
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func readinessHealthReadyGet(apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrObject?, _ error: Error?) -> Void)) -> RequestTask {
        return readinessHealthReadyGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Readiness
     - GET /health/ready
     - returns: RequestBuilder<SuccessResponseDictStrObject> 
     */
    open class func readinessHealthReadyGetWithRequestBuilder() -> RequestBuilder<SuccessResponseDictStrObject> {
        let localVariablePath = "/health/ready"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrObject>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
