//
// ManagementAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ManagementAPI {

    /**
     Add Permission To Role
     
     - parameter roleId: (path)  
     - parameter permissionId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addPermissionToRoleRolesRoleIdPermissionsPermissionIdPost(roleId: Int, permissionId: Int, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponsePermissionOut?, _ error: Error?) -> Void)) -> RequestTask {
        return addPermissionToRoleRolesRoleIdPermissionsPermissionIdPostWithRequestBuilder(roleId: roleId, permissionId: permissionId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add Permission To Role
     - POST /roles/{role_id}/permissions/{permission_id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter roleId: (path)  
     - parameter permissionId: (path)  
     - returns: RequestBuilder<SuccessResponsePermissionOut> 
     */
    open class func addPermissionToRoleRolesRoleIdPermissionsPermissionIdPostWithRequestBuilder(roleId: Int, permissionId: Int) -> RequestBuilder<SuccessResponsePermissionOut> {
        var localVariablePath = "/roles/{role_id}/permissions/{permission_id}"
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role_id}", with: roleIdPostEscape, options: .literal, range: nil)
        let permissionIdPreEscape = "\(APIHelper.mapValueToPathItem(permissionId))"
        let permissionIdPostEscape = permissionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{permission_id}", with: permissionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponsePermissionOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create Acl Entry
     
     - parameter aCLCreate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createAclEntryAclPost(aCLCreate: ACLCreate, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseACLOut?, _ error: Error?) -> Void)) -> RequestTask {
        return createAclEntryAclPostWithRequestBuilder(aCLCreate: aCLCreate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Acl Entry
     - POST /acl
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter aCLCreate: (body)  
     - returns: RequestBuilder<SuccessResponseACLOut> 
     */
    open class func createAclEntryAclPostWithRequestBuilder(aCLCreate: ACLCreate) -> RequestBuilder<SuccessResponseACLOut> {
        let localVariablePath = "/acl"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: aCLCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseACLOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create Auth Model
     
     - parameter authModelCreate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createAuthModelAuthModelPost(authModelCreate: AuthModelCreate, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseAuthModelOut?, _ error: Error?) -> Void)) -> RequestTask {
        return createAuthModelAuthModelPostWithRequestBuilder(authModelCreate: authModelCreate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Auth Model
     - POST /auth-model
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter authModelCreate: (body)  
     - returns: RequestBuilder<SuccessResponseAuthModelOut> 
     */
    open class func createAuthModelAuthModelPostWithRequestBuilder(authModelCreate: AuthModelCreate) -> RequestBuilder<SuccessResponseAuthModelOut> {
        let localVariablePath = "/auth-model"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: authModelCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseAuthModelOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create Permission
     
     - parameter permissionCreate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createPermissionPermissionsPost(permissionCreate: PermissionCreate, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: PermissionOut?, _ error: Error?) -> Void)) -> RequestTask {
        return createPermissionPermissionsPostWithRequestBuilder(permissionCreate: permissionCreate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Permission
     - POST /permissions
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter permissionCreate: (body)  
     - returns: RequestBuilder<PermissionOut> 
     */
    open class func createPermissionPermissionsPostWithRequestBuilder(permissionCreate: PermissionCreate) -> RequestBuilder<PermissionOut> {
        let localVariablePath = "/permissions"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: permissionCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PermissionOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create Policy From Dsl
     
     - parameter dsl: (query)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createPolicyFromDslPoliciesDslPost(dsl: String, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponsePolicyOut?, _ error: Error?) -> Void)) -> RequestTask {
        return createPolicyFromDslPoliciesDslPostWithRequestBuilder(dsl: dsl).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Policy From Dsl
     - POST /policies/dsl
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter dsl: (query)  
     - returns: RequestBuilder<SuccessResponsePolicyOut> 
     */
    open class func createPolicyFromDslPoliciesDslPostWithRequestBuilder(dsl: String) -> RequestBuilder<SuccessResponsePolicyOut> {
        let localVariablePath = "/policies/dsl"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "dsl": (wrappedValue: dsl.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponsePolicyOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create Policy
     
     - parameter policyCreate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createPolicyPoliciesPost(policyCreate: PolicyCreate, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponsePolicyOut?, _ error: Error?) -> Void)) -> RequestTask {
        return createPolicyPoliciesPostWithRequestBuilder(policyCreate: policyCreate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Policy
     - POST /policies
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter policyCreate: (body)  
     - returns: RequestBuilder<SuccessResponsePolicyOut> 
     */
    open class func createPolicyPoliciesPostWithRequestBuilder(policyCreate: PolicyCreate) -> RequestBuilder<SuccessResponsePolicyOut> {
        let localVariablePath = "/policies"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: policyCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponsePolicyOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create Relationship
     
     - parameter relationshipCreate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createRelationshipRelationshipsPost(relationshipCreate: RelationshipCreate, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseRelationshipOut?, _ error: Error?) -> Void)) -> RequestTask {
        return createRelationshipRelationshipsPostWithRequestBuilder(relationshipCreate: relationshipCreate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Relationship
     - POST /relationships
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter relationshipCreate: (body)  
     - returns: RequestBuilder<SuccessResponseRelationshipOut> 
     */
    open class func createRelationshipRelationshipsPostWithRequestBuilder(relationshipCreate: RelationshipCreate) -> RequestBuilder<SuccessResponseRelationshipOut> {
        let localVariablePath = "/relationships"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: relationshipCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseRelationshipOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create Role
     
     - parameter roleCreate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createRoleRolesPost(roleCreate: RoleCreate, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: RoleOut?, _ error: Error?) -> Void)) -> RequestTask {
        return createRoleRolesPostWithRequestBuilder(roleCreate: roleCreate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Role
     - POST /roles
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter roleCreate: (body)  
     - returns: RequestBuilder<RoleOut> 
     */
    open class func createRoleRolesPostWithRequestBuilder(roleCreate: RoleCreate) -> RequestBuilder<RoleOut> {
        let localVariablePath = "/roles"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: roleCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoleOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Acl Entry
     
     - parameter aclId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteAclEntryAclAclIdDelete(aclId: Int, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrInt?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteAclEntryAclAclIdDeleteWithRequestBuilder(aclId: aclId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete Acl Entry
     - DELETE /acl/{acl_id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter aclId: (path)  
     - returns: RequestBuilder<SuccessResponseDictStrInt> 
     */
    open class func deleteAclEntryAclAclIdDeleteWithRequestBuilder(aclId: Int) -> RequestBuilder<SuccessResponseDictStrInt> {
        var localVariablePath = "/acl/{acl_id}"
        let aclIdPreEscape = "\(APIHelper.mapValueToPathItem(aclId))"
        let aclIdPostEscape = aclIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{acl_id}", with: aclIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrInt>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Permission
     
     - parameter permissionId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deletePermissionPermissionsPermissionIdDelete(permissionId: Int, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrInt?, _ error: Error?) -> Void)) -> RequestTask {
        return deletePermissionPermissionsPermissionIdDeleteWithRequestBuilder(permissionId: permissionId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete Permission
     - DELETE /permissions/{permission_id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter permissionId: (path)  
     - returns: RequestBuilder<SuccessResponseDictStrInt> 
     */
    open class func deletePermissionPermissionsPermissionIdDeleteWithRequestBuilder(permissionId: Int) -> RequestBuilder<SuccessResponseDictStrInt> {
        var localVariablePath = "/permissions/{permission_id}"
        let permissionIdPreEscape = "\(APIHelper.mapValueToPathItem(permissionId))"
        let permissionIdPostEscape = permissionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{permission_id}", with: permissionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrInt>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Policy
     
     - parameter policyKey: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deletePolicyPoliciesPolicyKeyDelete(policyKey: String, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrStr?, _ error: Error?) -> Void)) -> RequestTask {
        return deletePolicyPoliciesPolicyKeyDeleteWithRequestBuilder(policyKey: policyKey).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete Policy
     - DELETE /policies/{policy_key}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter policyKey: (path)  
     - returns: RequestBuilder<SuccessResponseDictStrStr> 
     */
    open class func deletePolicyPoliciesPolicyKeyDeleteWithRequestBuilder(policyKey: String) -> RequestBuilder<SuccessResponseDictStrStr> {
        var localVariablePath = "/policies/{policy_key}"
        let policyKeyPreEscape = "\(APIHelper.mapValueToPathItem(policyKey))"
        let policyKeyPostEscape = policyKeyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{policy_key}", with: policyKeyPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrStr>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Role
     
     - parameter roleId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteRoleRolesRoleIdDelete(roleId: Int, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrInt?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteRoleRolesRoleIdDeleteWithRequestBuilder(roleId: roleId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete Role
     - DELETE /roles/{role_id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter roleId: (path)  
     - returns: RequestBuilder<SuccessResponseDictStrInt> 
     */
    open class func deleteRoleRolesRoleIdDeleteWithRequestBuilder(roleId: Int) -> RequestBuilder<SuccessResponseDictStrInt> {
        var localVariablePath = "/roles/{role_id}"
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role_id}", with: roleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrInt>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Auth Model
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAuthModelAuthModelGet(apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseAuthModelOut?, _ error: Error?) -> Void)) -> RequestTask {
        return getAuthModelAuthModelGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Auth Model
     - GET /auth-model
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - returns: RequestBuilder<SuccessResponseAuthModelOut> 
     */
    open class func getAuthModelAuthModelGetWithRequestBuilder() -> RequestBuilder<SuccessResponseAuthModelOut> {
        let localVariablePath = "/auth-model"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseAuthModelOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Impact Analysis
     
     - parameter impactAnalysisRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func impactAnalysisImpactAnalysisPost(impactAnalysisRequest: ImpactAnalysisRequest, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseImpactAnalysisResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return impactAnalysisImpactAnalysisPostWithRequestBuilder(impactAnalysisRequest: impactAnalysisRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Impact Analysis
     - POST /impact-analysis
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter impactAnalysisRequest: (body)  
     - returns: RequestBuilder<SuccessResponseImpactAnalysisResponse> 
     */
    open class func impactAnalysisImpactAnalysisPostWithRequestBuilder(impactAnalysisRequest: ImpactAnalysisRequest) -> RequestBuilder<SuccessResponseImpactAnalysisResponse> {
        let localVariablePath = "/impact-analysis"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: impactAnalysisRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseImpactAnalysisResponse>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Acl Entries
     
     - parameter resourceType: (path)  
     - parameter resourceId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listAclEntriesAclResourceTypeResourceIdGet(resourceType: String, resourceId: String, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseListACLOut?, _ error: Error?) -> Void)) -> RequestTask {
        return listAclEntriesAclResourceTypeResourceIdGetWithRequestBuilder(resourceType: resourceType, resourceId: resourceId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List Acl Entries
     - GET /acl/{resource_type}/{resource_id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter resourceType: (path)  
     - parameter resourceId: (path)  
     - returns: RequestBuilder<SuccessResponseListACLOut> 
     */
    open class func listAclEntriesAclResourceTypeResourceIdGetWithRequestBuilder(resourceType: String, resourceId: String) -> RequestBuilder<SuccessResponseListACLOut> {
        var localVariablePath = "/acl/{resource_type}/{resource_id}"
        let resourceTypePreEscape = "\(APIHelper.mapValueToPathItem(resourceType))"
        let resourceTypePostEscape = resourceTypePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{resource_type}", with: resourceTypePostEscape, options: .literal, range: nil)
        let resourceIdPreEscape = "\(APIHelper.mapValueToPathItem(resourceId))"
        let resourceIdPostEscape = resourceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{resource_id}", with: resourceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseListACLOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Audit Logs
     
     - parameter limit: (query)  (optional, default to 50)
     - parameter cursor: (query)  (optional)
     - parameter userId: (query)  (optional)
     - parameter resourceId: (query)  (optional)
     - parameter decision: (query)  (optional)
     - parameter startTime: (query)  (optional)
     - parameter endTime: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listAuditLogsAuditGet(limit: Int? = nil, cursor: String? = nil, userId: String? = nil, resourceId: String? = nil, decision: String? = nil, startTime: Date? = nil, endTime: Date? = nil, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseListAuditRecordOut?, _ error: Error?) -> Void)) -> RequestTask {
        return listAuditLogsAuditGetWithRequestBuilder(limit: limit, cursor: cursor, userId: userId, resourceId: resourceId, decision: decision, startTime: startTime, endTime: endTime).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List Audit Logs
     - GET /audit
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter limit: (query)  (optional, default to 50)
     - parameter cursor: (query)  (optional)
     - parameter userId: (query)  (optional)
     - parameter resourceId: (query)  (optional)
     - parameter decision: (query)  (optional)
     - parameter startTime: (query)  (optional)
     - parameter endTime: (query)  (optional)
     - returns: RequestBuilder<SuccessResponseListAuditRecordOut> 
     */
    open class func listAuditLogsAuditGetWithRequestBuilder(limit: Int? = nil, cursor: String? = nil, userId: String? = nil, resourceId: String? = nil, decision: String? = nil, startTime: Date? = nil, endTime: Date? = nil) -> RequestBuilder<SuccessResponseListAuditRecordOut> {
        let localVariablePath = "/audit"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "user_id": (wrappedValue: userId?.encodeToJSON(), isExplode: true),
            "resource_id": (wrappedValue: resourceId?.encodeToJSON(), isExplode: true),
            "decision": (wrappedValue: decision?.encodeToJSON(), isExplode: true),
            "start_time": (wrappedValue: startTime?.encodeToJSON(), isExplode: true),
            "end_time": (wrappedValue: endTime?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseListAuditRecordOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Permission Roles
     
     - parameter permissionId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listPermissionRolesPermissionsPermissionIdRolesGet(permissionId: Int, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseListRoleOut?, _ error: Error?) -> Void)) -> RequestTask {
        return listPermissionRolesPermissionsPermissionIdRolesGetWithRequestBuilder(permissionId: permissionId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List Permission Roles
     - GET /permissions/{permission_id}/roles
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter permissionId: (path)  
     - returns: RequestBuilder<SuccessResponseListRoleOut> 
     */
    open class func listPermissionRolesPermissionsPermissionIdRolesGetWithRequestBuilder(permissionId: Int) -> RequestBuilder<SuccessResponseListRoleOut> {
        var localVariablePath = "/permissions/{permission_id}/roles"
        let permissionIdPreEscape = "\(APIHelper.mapValueToPathItem(permissionId))"
        let permissionIdPostEscape = permissionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{permission_id}", with: permissionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseListRoleOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Permissions
     
     - parameter limit: (query)  (optional, default to 50)
     - parameter cursor: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listPermissionsPermissionsGet(limit: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseListPermissionOut?, _ error: Error?) -> Void)) -> RequestTask {
        return listPermissionsPermissionsGetWithRequestBuilder(limit: limit, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List Permissions
     - GET /permissions
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter limit: (query)  (optional, default to 50)
     - parameter cursor: (query)  (optional)
     - returns: RequestBuilder<SuccessResponseListPermissionOut> 
     */
    open class func listPermissionsPermissionsGetWithRequestBuilder(limit: Int? = nil, cursor: String? = nil) -> RequestBuilder<SuccessResponseListPermissionOut> {
        let localVariablePath = "/permissions"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseListPermissionOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Policies
     
     - parameter limit: (query)  (optional, default to 50)
     - parameter cursor: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listPoliciesPoliciesGet(limit: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseListPolicyOut?, _ error: Error?) -> Void)) -> RequestTask {
        return listPoliciesPoliciesGetWithRequestBuilder(limit: limit, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List Policies
     - GET /policies
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter limit: (query)  (optional, default to 50)
     - parameter cursor: (query)  (optional)
     - returns: RequestBuilder<SuccessResponseListPolicyOut> 
     */
    open class func listPoliciesPoliciesGetWithRequestBuilder(limit: Int? = nil, cursor: String? = nil) -> RequestBuilder<SuccessResponseListPolicyOut> {
        let localVariablePath = "/policies"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseListPolicyOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Relationships
     
     - parameter subjectType: (query)  
     - parameter subjectId: (query)  
     - parameter limit: (query)  (optional, default to 50)
     - parameter cursor: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listRelationshipsRelationshipsGet(subjectType: String, subjectId: String, limit: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseListDictStrStr?, _ error: Error?) -> Void)) -> RequestTask {
        return listRelationshipsRelationshipsGetWithRequestBuilder(subjectType: subjectType, subjectId: subjectId, limit: limit, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List Relationships
     - GET /relationships
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter subjectType: (query)  
     - parameter subjectId: (query)  
     - parameter limit: (query)  (optional, default to 50)
     - parameter cursor: (query)  (optional)
     - returns: RequestBuilder<SuccessResponseListDictStrStr> 
     */
    open class func listRelationshipsRelationshipsGetWithRequestBuilder(subjectType: String, subjectId: String, limit: Int? = nil, cursor: String? = nil) -> RequestBuilder<SuccessResponseListDictStrStr> {
        let localVariablePath = "/relationships"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "subject_type": (wrappedValue: subjectType.encodeToJSON(), isExplode: true),
            "subject_id": (wrappedValue: subjectId.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseListDictStrStr>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Role Permissions
     
     - parameter roleId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listRolePermissionsRolesRoleIdPermissionsGet(roleId: Int, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseListPermissionOut?, _ error: Error?) -> Void)) -> RequestTask {
        return listRolePermissionsRolesRoleIdPermissionsGetWithRequestBuilder(roleId: roleId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List Role Permissions
     - GET /roles/{role_id}/permissions
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter roleId: (path)  
     - returns: RequestBuilder<SuccessResponseListPermissionOut> 
     */
    open class func listRolePermissionsRolesRoleIdPermissionsGetWithRequestBuilder(roleId: Int) -> RequestBuilder<SuccessResponseListPermissionOut> {
        var localVariablePath = "/roles/{role_id}/permissions"
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role_id}", with: roleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseListPermissionOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Roles
     
     - parameter limit: (query)  (optional, default to 50)
     - parameter cursor: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listRolesRolesGet(limit: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseListRoleOut?, _ error: Error?) -> Void)) -> RequestTask {
        return listRolesRolesGetWithRequestBuilder(limit: limit, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List Roles
     - GET /roles
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter limit: (query)  (optional, default to 50)
     - parameter cursor: (query)  (optional)
     - returns: RequestBuilder<SuccessResponseListRoleOut> 
     */
    open class func listRolesRolesGetWithRequestBuilder(limit: Int? = nil, cursor: String? = nil) -> RequestBuilder<SuccessResponseListRoleOut> {
        let localVariablePath = "/roles"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseListRoleOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Remove Permission From Role
     
     - parameter roleId: (path)  
     - parameter permissionId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func removePermissionFromRoleRolesRoleIdPermissionsPermissionIdDelete(roleId: Int, permissionId: Int, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrInt?, _ error: Error?) -> Void)) -> RequestTask {
        return removePermissionFromRoleRolesRoleIdPermissionsPermissionIdDeleteWithRequestBuilder(roleId: roleId, permissionId: permissionId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Remove Permission From Role
     - DELETE /roles/{role_id}/permissions/{permission_id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter roleId: (path)  
     - parameter permissionId: (path)  
     - returns: RequestBuilder<SuccessResponseDictStrInt> 
     */
    open class func removePermissionFromRoleRolesRoleIdPermissionsPermissionIdDeleteWithRequestBuilder(roleId: Int, permissionId: Int) -> RequestBuilder<SuccessResponseDictStrInt> {
        var localVariablePath = "/roles/{role_id}/permissions/{permission_id}"
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role_id}", with: roleIdPostEscape, options: .literal, range: nil)
        let permissionIdPreEscape = "\(APIHelper.mapValueToPathItem(permissionId))"
        let permissionIdPostEscape = permissionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{permission_id}", with: permissionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrInt>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Rollback Policy
     
     - parameter policyKey: (path)  
     - parameter version: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func rollbackPolicyPoliciesPolicyKeyRollbackVersionPost(policyKey: String, version: Int, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrUnionIntStr?, _ error: Error?) -> Void)) -> RequestTask {
        return rollbackPolicyPoliciesPolicyKeyRollbackVersionPostWithRequestBuilder(policyKey: policyKey, version: version).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Rollback Policy
     - POST /policies/{policy_key}/rollback/{version}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter policyKey: (path)  
     - parameter version: (path)  
     - returns: RequestBuilder<SuccessResponseDictStrUnionIntStr> 
     */
    open class func rollbackPolicyPoliciesPolicyKeyRollbackVersionPostWithRequestBuilder(policyKey: String, version: Int) -> RequestBuilder<SuccessResponseDictStrUnionIntStr> {
        var localVariablePath = "/policies/{policy_key}/rollback/{version}"
        let policyKeyPreEscape = "\(APIHelper.mapValueToPathItem(policyKey))"
        let policyKeyPostEscape = policyKeyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{policy_key}", with: policyKeyPostEscape, options: .literal, range: nil)
        let versionPreEscape = "\(APIHelper.mapValueToPathItem(version))"
        let versionPostEscape = versionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{version}", with: versionPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrUnionIntStr>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Simulate Policy
     
     - parameter policySimulationRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func simulatePolicySimulatePolicyPost(policySimulationRequest: PolicySimulationRequest, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponsePolicySimulationResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return simulatePolicySimulatePolicyPostWithRequestBuilder(policySimulationRequest: policySimulationRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Simulate Policy
     - POST /simulate-policy
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter policySimulationRequest: (body)  
     - returns: RequestBuilder<SuccessResponsePolicySimulationResponse> 
     */
    open class func simulatePolicySimulatePolicyPostWithRequestBuilder(policySimulationRequest: PolicySimulationRequest) -> RequestBuilder<SuccessResponsePolicySimulationResponse> {
        let localVariablePath = "/simulate-policy"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: policySimulationRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponsePolicySimulationResponse>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Permission
     
     - parameter permissionId: (path)  
     - parameter permissionUpdate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updatePermissionPermissionsPermissionIdPut(permissionId: Int, permissionUpdate: PermissionUpdate, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: PermissionOut?, _ error: Error?) -> Void)) -> RequestTask {
        return updatePermissionPermissionsPermissionIdPutWithRequestBuilder(permissionId: permissionId, permissionUpdate: permissionUpdate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update Permission
     - PUT /permissions/{permission_id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter permissionId: (path)  
     - parameter permissionUpdate: (body)  
     - returns: RequestBuilder<PermissionOut> 
     */
    open class func updatePermissionPermissionsPermissionIdPutWithRequestBuilder(permissionId: Int, permissionUpdate: PermissionUpdate) -> RequestBuilder<PermissionOut> {
        var localVariablePath = "/permissions/{permission_id}"
        let permissionIdPreEscape = "\(APIHelper.mapValueToPathItem(permissionId))"
        let permissionIdPostEscape = permissionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{permission_id}", with: permissionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: permissionUpdate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PermissionOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Policy
     
     - parameter policyKey: (path)  
     - parameter policyCreate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updatePolicyPoliciesPolicyKeyPut(policyKey: String, policyCreate: PolicyCreate, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponsePolicyOut?, _ error: Error?) -> Void)) -> RequestTask {
        return updatePolicyPoliciesPolicyKeyPutWithRequestBuilder(policyKey: policyKey, policyCreate: policyCreate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update Policy
     - PUT /policies/{policy_key}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter policyKey: (path)  
     - parameter policyCreate: (body)  
     - returns: RequestBuilder<SuccessResponsePolicyOut> 
     */
    open class func updatePolicyPoliciesPolicyKeyPutWithRequestBuilder(policyKey: String, policyCreate: PolicyCreate) -> RequestBuilder<SuccessResponsePolicyOut> {
        var localVariablePath = "/policies/{policy_key}"
        let policyKeyPreEscape = "\(APIHelper.mapValueToPathItem(policyKey))"
        let policyKeyPostEscape = policyKeyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{policy_key}", with: policyKeyPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: policyCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponsePolicyOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Role
     
     - parameter roleId: (path)  
     - parameter roleUpdate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateRoleRolesRoleIdPut(roleId: Int, roleUpdate: RoleUpdate, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: RoleOut?, _ error: Error?) -> Void)) -> RequestTask {
        return updateRoleRolesRoleIdPutWithRequestBuilder(roleId: roleId, roleUpdate: roleUpdate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update Role
     - PUT /roles/{role_id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter roleId: (path)  
     - parameter roleUpdate: (body)  
     - returns: RequestBuilder<RoleOut> 
     */
    open class func updateRoleRolesRoleIdPutWithRequestBuilder(roleId: Int, roleUpdate: RoleUpdate) -> RequestBuilder<RoleOut> {
        var localVariablePath = "/roles/{role_id}"
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role_id}", with: roleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: roleUpdate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoleOut>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
