//
// PlaygroundAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PlaygroundAPI {

    /**
     Evaluate
     
     - parameter playgroundEvaluateRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func evaluatePlaygroundEvaluatePost(playgroundEvaluateRequest: PlaygroundEvaluateRequest, apiResponseQueue: DispatchQueue = KeyNetraClientAPI.apiResponseQueue, completion: @escaping ((_ data: SuccessResponseDictStrAny?, _ error: Error?) -> Void)) -> RequestTask {
        return evaluatePlaygroundEvaluatePostWithRequestBuilder(playgroundEvaluateRequest: playgroundEvaluateRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Evaluate
     - POST /playground/evaluate
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: APIKeyHeader
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter playgroundEvaluateRequest: (body)  
     - returns: RequestBuilder<SuccessResponseDictStrAny> 
     */
    open class func evaluatePlaygroundEvaluatePostWithRequestBuilder(playgroundEvaluateRequest: PlaygroundEvaluateRequest) -> RequestBuilder<SuccessResponseDictStrAny> {
        let localVariablePath = "/playground/evaluate"
        let localVariableURLString = KeyNetraClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: playgroundEvaluateRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessResponseDictStrAny>.Type = KeyNetraClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
