=begin
#KeyNetra

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KeyNetra::PlaygroundApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PlaygroundApi' do
  before do
    # run before each test
    @api_instance = KeyNetra::PlaygroundApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PlaygroundApi' do
    it 'should create an instance of PlaygroundApi' do
      expect(@api_instance).to be_instance_of(KeyNetra::PlaygroundApi)
    end
  end

  # unit tests for evaluate_playground_evaluate_post
  # Evaluate
  # @param playground_evaluate_request 
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponseDictStrAny]
  describe 'evaluate_playground_evaluate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
