# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AuditRecordOut(BaseModel):
    """
    AuditRecordOut
    """ # noqa: E501
    id: StrictInt
    principal_type: StrictStr
    principal_id: StrictStr
    correlation_id: Optional[StrictStr] = None
    user: Dict[str, Any]
    action: StrictStr
    resource: Dict[str, Any]
    decision: StrictStr
    matched_policies: List[Any]
    reason: Optional[StrictStr] = None
    evaluated_rules: List[Any]
    failed_conditions: List[Any]
    created_at: datetime
    __properties: ClassVar[List[str]] = ["id", "principal_type", "principal_id", "correlation_id", "user", "action", "resource", "decision", "matched_policies", "reason", "evaluated_rules", "failed_conditions", "created_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuditRecordOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if correlation_id (nullable) is None
        # and model_fields_set contains the field
        if self.correlation_id is None and "correlation_id" in self.model_fields_set:
            _dict['correlation_id'] = None

        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuditRecordOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "principal_type": obj.get("principal_type"),
            "principal_id": obj.get("principal_id"),
            "correlation_id": obj.get("correlation_id"),
            "user": obj.get("user"),
            "action": obj.get("action"),
            "resource": obj.get("resource"),
            "decision": obj.get("decision"),
            "matched_policies": obj.get("matched_policies"),
            "reason": obj.get("reason"),
            "evaluated_rules": obj.get("evaluated_rules"),
            "failed_conditions": obj.get("failed_conditions"),
            "created_at": obj.get("created_at")
        })
        return _obj


