# coding: utf-8

"""
    KeyNetra

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PolicySimulationInput(BaseModel):
    """
    PolicySimulationInput
    """ # noqa: E501
    policy_change: Optional[StrictStr] = None
    relationship_change: Optional[Dict[str, Any]] = None
    role_change: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["policy_change", "relationship_change", "role_change"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PolicySimulationInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if policy_change (nullable) is None
        # and model_fields_set contains the field
        if self.policy_change is None and "policy_change" in self.model_fields_set:
            _dict['policy_change'] = None

        # set to None if relationship_change (nullable) is None
        # and model_fields_set contains the field
        if self.relationship_change is None and "relationship_change" in self.model_fields_set:
            _dict['relationship_change'] = None

        # set to None if role_change (nullable) is None
        # and model_fields_set contains the field
        if self.role_change is None and "role_change" in self.model_fields_set:
            _dict['role_change'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PolicySimulationInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "policy_change": obj.get("policy_change"),
            "relationship_change": obj.get("relationship_change"),
            "role_change": obj.get("role_change")
        })
        return _obj


