packageName: keynetra
packageVersion: 0.1.1
moduleName: github.com/keynetra/keynetra-client-go
enumClassPrefix: true
generateInterfaces: true
hideGenerationTimestamp: true
withGoMod: true
packageDescription: "Official Go Client SDK for KeyNetra authorization platform."
packageAuthor: "KeyNetra"
packageEmail: "business.keynetra@gmail.com"
packageUrl: "https://github.com/keynetra/keynetra-client-go"
