/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type AccessAPI interface {

	/*
	CheckAccessBatchCheckAccessBatchPost Check Access Batch

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCheckAccessBatchCheckAccessBatchPostRequest
	*/
	CheckAccessBatchCheckAccessBatchPost(ctx context.Context) ApiCheckAccessBatchCheckAccessBatchPostRequest

	// CheckAccessBatchCheckAccessBatchPostExecute executes the request
	//  @return SuccessResponseBatchAccessResponse
	CheckAccessBatchCheckAccessBatchPostExecute(r ApiCheckAccessBatchCheckAccessBatchPostRequest) (*SuccessResponseBatchAccessResponse, *http.Response, error)

	/*
	CheckAccessCheckAccessPost Check Access

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCheckAccessCheckAccessPostRequest
	*/
	CheckAccessCheckAccessPost(ctx context.Context) ApiCheckAccessCheckAccessPostRequest

	// CheckAccessCheckAccessPostExecute executes the request
	//  @return SuccessResponseAccessDecisionResponse
	CheckAccessCheckAccessPostExecute(r ApiCheckAccessCheckAccessPostRequest) (*SuccessResponseAccessDecisionResponse, *http.Response, error)

	/*
	SimulateSimulatePost Simulate

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiSimulateSimulatePostRequest
	*/
	SimulateSimulatePost(ctx context.Context) ApiSimulateSimulatePostRequest

	// SimulateSimulatePostExecute executes the request
	//  @return SuccessResponseSimulationResponse
	SimulateSimulatePostExecute(r ApiSimulateSimulatePostRequest) (*SuccessResponseSimulationResponse, *http.Response, error)
}

// AccessAPIService AccessAPI service
type AccessAPIService service

type ApiCheckAccessBatchCheckAccessBatchPostRequest struct {
	ctx context.Context
	ApiService AccessAPI
	batchAccessRequest *BatchAccessRequest
	policySet *string
}

func (r ApiCheckAccessBatchCheckAccessBatchPostRequest) BatchAccessRequest(batchAccessRequest BatchAccessRequest) ApiCheckAccessBatchCheckAccessBatchPostRequest {
	r.batchAccessRequest = &batchAccessRequest
	return r
}

func (r ApiCheckAccessBatchCheckAccessBatchPostRequest) PolicySet(policySet string) ApiCheckAccessBatchCheckAccessBatchPostRequest {
	r.policySet = &policySet
	return r
}

func (r ApiCheckAccessBatchCheckAccessBatchPostRequest) Execute() (*SuccessResponseBatchAccessResponse, *http.Response, error) {
	return r.ApiService.CheckAccessBatchCheckAccessBatchPostExecute(r)
}

/*
CheckAccessBatchCheckAccessBatchPost Check Access Batch

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCheckAccessBatchCheckAccessBatchPostRequest
*/
func (a *AccessAPIService) CheckAccessBatchCheckAccessBatchPost(ctx context.Context) ApiCheckAccessBatchCheckAccessBatchPostRequest {
	return ApiCheckAccessBatchCheckAccessBatchPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SuccessResponseBatchAccessResponse
func (a *AccessAPIService) CheckAccessBatchCheckAccessBatchPostExecute(r ApiCheckAccessBatchCheckAccessBatchPostRequest) (*SuccessResponseBatchAccessResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SuccessResponseBatchAccessResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccessAPIService.CheckAccessBatchCheckAccessBatchPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/check-access-batch"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.batchAccessRequest == nil {
		return localVarReturnValue, nil, reportError("batchAccessRequest is required and must be specified")
	}

	if r.policySet != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "policy_set", r.policySet, "form", "")
	} else {
		var defaultValue string = "active"
		parameterAddToHeaderOrQuery(localVarQueryParams, "policy_set", defaultValue, "form", "")
		r.policySet = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.batchAccessRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCheckAccessCheckAccessPostRequest struct {
	ctx context.Context
	ApiService AccessAPI
	accessRequest *AccessRequest
	policySet *string
}

func (r ApiCheckAccessCheckAccessPostRequest) AccessRequest(accessRequest AccessRequest) ApiCheckAccessCheckAccessPostRequest {
	r.accessRequest = &accessRequest
	return r
}

func (r ApiCheckAccessCheckAccessPostRequest) PolicySet(policySet string) ApiCheckAccessCheckAccessPostRequest {
	r.policySet = &policySet
	return r
}

func (r ApiCheckAccessCheckAccessPostRequest) Execute() (*SuccessResponseAccessDecisionResponse, *http.Response, error) {
	return r.ApiService.CheckAccessCheckAccessPostExecute(r)
}

/*
CheckAccessCheckAccessPost Check Access

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCheckAccessCheckAccessPostRequest
*/
func (a *AccessAPIService) CheckAccessCheckAccessPost(ctx context.Context) ApiCheckAccessCheckAccessPostRequest {
	return ApiCheckAccessCheckAccessPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SuccessResponseAccessDecisionResponse
func (a *AccessAPIService) CheckAccessCheckAccessPostExecute(r ApiCheckAccessCheckAccessPostRequest) (*SuccessResponseAccessDecisionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SuccessResponseAccessDecisionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccessAPIService.CheckAccessCheckAccessPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/check-access"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.accessRequest == nil {
		return localVarReturnValue, nil, reportError("accessRequest is required and must be specified")
	}

	if r.policySet != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "policy_set", r.policySet, "form", "")
	} else {
		var defaultValue string = "active"
		parameterAddToHeaderOrQuery(localVarQueryParams, "policy_set", defaultValue, "form", "")
		r.policySet = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.accessRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiSimulateSimulatePostRequest struct {
	ctx context.Context
	ApiService AccessAPI
	accessRequest *AccessRequest
}

func (r ApiSimulateSimulatePostRequest) AccessRequest(accessRequest AccessRequest) ApiSimulateSimulatePostRequest {
	r.accessRequest = &accessRequest
	return r
}

func (r ApiSimulateSimulatePostRequest) Execute() (*SuccessResponseSimulationResponse, *http.Response, error) {
	return r.ApiService.SimulateSimulatePostExecute(r)
}

/*
SimulateSimulatePost Simulate

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiSimulateSimulatePostRequest
*/
func (a *AccessAPIService) SimulateSimulatePost(ctx context.Context) ApiSimulateSimulatePostRequest {
	return ApiSimulateSimulatePostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SuccessResponseSimulationResponse
func (a *AccessAPIService) SimulateSimulatePostExecute(r ApiSimulateSimulatePostRequest) (*SuccessResponseSimulationResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SuccessResponseSimulationResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccessAPIService.SimulateSimulatePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/simulate"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.accessRequest == nil {
		return localVarReturnValue, nil, reportError("accessRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.accessRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
