/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type AuthAPI interface {

	/*
	AdminLoginAdminLoginPost Admin Login

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAdminLoginAdminLoginPostRequest
	*/
	AdminLoginAdminLoginPost(ctx context.Context) ApiAdminLoginAdminLoginPostRequest

	// AdminLoginAdminLoginPostExecute executes the request
	//  @return SuccessResponseAdminLoginResponse
	AdminLoginAdminLoginPostExecute(r ApiAdminLoginAdminLoginPostRequest) (*SuccessResponseAdminLoginResponse, *http.Response, error)

	/*
	AdminLoginAdminLoginPost_0 Admin Login

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAdminLoginAdminLoginPost_0Request
	*/
	AdminLoginAdminLoginPost_1(ctx context.Context) ApiAdminLoginAdminLoginPost_0Request

	// AdminLoginAdminLoginPost_1Execute executes the request
	//  @return SuccessResponseAdminLoginResponse
	AdminLoginAdminLoginPost_1Execute(r ApiAdminLoginAdminLoginPost_0Request) (*SuccessResponseAdminLoginResponse, *http.Response, error)
}

// AuthAPIService AuthAPI service
type AuthAPIService service

type ApiAdminLoginAdminLoginPostRequest struct {
	ctx context.Context
	ApiService AuthAPI
	adminLoginRequest *AdminLoginRequest
}

func (r ApiAdminLoginAdminLoginPostRequest) AdminLoginRequest(adminLoginRequest AdminLoginRequest) ApiAdminLoginAdminLoginPostRequest {
	r.adminLoginRequest = &adminLoginRequest
	return r
}

func (r ApiAdminLoginAdminLoginPostRequest) Execute() (*SuccessResponseAdminLoginResponse, *http.Response, error) {
	return r.ApiService.AdminLoginAdminLoginPostExecute(r)
}

/*
AdminLoginAdminLoginPost Admin Login

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAdminLoginAdminLoginPostRequest
*/
func (a *AuthAPIService) AdminLoginAdminLoginPost(ctx context.Context) ApiAdminLoginAdminLoginPostRequest {
	return ApiAdminLoginAdminLoginPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SuccessResponseAdminLoginResponse
func (a *AuthAPIService) AdminLoginAdminLoginPostExecute(r ApiAdminLoginAdminLoginPostRequest) (*SuccessResponseAdminLoginResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SuccessResponseAdminLoginResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthAPIService.AdminLoginAdminLoginPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/admin/login"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.adminLoginRequest == nil {
		return localVarReturnValue, nil, reportError("adminLoginRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.adminLoginRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAdminLoginAdminLoginPost_0Request struct {
	ctx context.Context
	ApiService AuthAPI
	adminLoginRequest *AdminLoginRequest
}

func (r ApiAdminLoginAdminLoginPost_0Request) AdminLoginRequest(adminLoginRequest AdminLoginRequest) ApiAdminLoginAdminLoginPost_0Request {
	r.adminLoginRequest = &adminLoginRequest
	return r
}

func (r ApiAdminLoginAdminLoginPost_0Request) Execute() (*SuccessResponseAdminLoginResponse, *http.Response, error) {
	return r.ApiService.AdminLoginAdminLoginPost_1Execute(r)
}

/*
AdminLoginAdminLoginPost_0 Admin Login

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAdminLoginAdminLoginPost_0Request
*/
func (a *AuthAPIService) AdminLoginAdminLoginPost_1(ctx context.Context) ApiAdminLoginAdminLoginPost_0Request {
	return ApiAdminLoginAdminLoginPost_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SuccessResponseAdminLoginResponse
func (a *AuthAPIService) AdminLoginAdminLoginPost_1Execute(r ApiAdminLoginAdminLoginPost_0Request) (*SuccessResponseAdminLoginResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SuccessResponseAdminLoginResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthAPIService.AdminLoginAdminLoginPost_1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/admin/login"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.adminLoginRequest == nil {
		return localVarReturnValue, nil, reportError("adminLoginRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.adminLoginRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
