/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SuccessResponseDictStrAny type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessResponseDictStrAny{}

// SuccessResponseDictStrAny struct for SuccessResponseDictStrAny
type SuccessResponseDictStrAny struct {
	Data map[string]interface{} `json:"data"`
	Meta *MetaBody `json:"meta,omitempty"`
	Error *interface{} `json:"error,omitempty"`
}

type _SuccessResponseDictStrAny SuccessResponseDictStrAny

// NewSuccessResponseDictStrAny instantiates a new SuccessResponseDictStrAny object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessResponseDictStrAny(data map[string]interface{}) *SuccessResponseDictStrAny {
	this := SuccessResponseDictStrAny{}
	this.Data = data
	return &this
}

// NewSuccessResponseDictStrAnyWithDefaults instantiates a new SuccessResponseDictStrAny object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessResponseDictStrAnyWithDefaults() *SuccessResponseDictStrAny {
	this := SuccessResponseDictStrAny{}
	return &this
}

// GetData returns the Data field value
func (o *SuccessResponseDictStrAny) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SuccessResponseDictStrAny) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SuccessResponseDictStrAny) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SuccessResponseDictStrAny) GetMeta() MetaBody {
	if o == nil || IsNil(o.Meta) {
		var ret MetaBody
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseDictStrAny) GetMetaOk() (*MetaBody, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SuccessResponseDictStrAny) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaBody and assigns it to the Meta field.
func (o *SuccessResponseDictStrAny) SetMeta(v MetaBody) {
	o.Meta = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SuccessResponseDictStrAny) GetError() interface{} {
	if o == nil || IsNil(o.Error) {
		var ret interface{}
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseDictStrAny) GetErrorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SuccessResponseDictStrAny) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given interface{} and assigns it to the Error field.
func (o *SuccessResponseDictStrAny) SetError(v interface{}) {
	o.Error = &v
}

func (o SuccessResponseDictStrAny) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessResponseDictStrAny) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *SuccessResponseDictStrAny) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessResponseDictStrAny := _SuccessResponseDictStrAny{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSuccessResponseDictStrAny)

	if err != nil {
		return err
	}

	*o = SuccessResponseDictStrAny(varSuccessResponseDictStrAny)

	return err
}

type NullableSuccessResponseDictStrAny struct {
	value *SuccessResponseDictStrAny
	isSet bool
}

func (v NullableSuccessResponseDictStrAny) Get() *SuccessResponseDictStrAny {
	return v.value
}

func (v *NullableSuccessResponseDictStrAny) Set(val *SuccessResponseDictStrAny) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessResponseDictStrAny) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessResponseDictStrAny) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessResponseDictStrAny(val *SuccessResponseDictStrAny) *NullableSuccessResponseDictStrAny {
	return &NullableSuccessResponseDictStrAny{value: val, isSet: true}
}

func (v NullableSuccessResponseDictStrAny) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessResponseDictStrAny) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


