/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
)

// checks if the ImpactAnalysisResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImpactAnalysisResponse{}

// ImpactAnalysisResponse struct for ImpactAnalysisResponse
type ImpactAnalysisResponse struct {
	GainedAccess []int32 `json:"gained_access,omitempty"`
	LostAccess []int32 `json:"lost_access,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ImpactAnalysisResponse ImpactAnalysisResponse

// NewImpactAnalysisResponse instantiates a new ImpactAnalysisResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImpactAnalysisResponse() *ImpactAnalysisResponse {
	this := ImpactAnalysisResponse{}
	return &this
}

// NewImpactAnalysisResponseWithDefaults instantiates a new ImpactAnalysisResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImpactAnalysisResponseWithDefaults() *ImpactAnalysisResponse {
	this := ImpactAnalysisResponse{}
	return &this
}

// GetGainedAccess returns the GainedAccess field value if set, zero value otherwise.
func (o *ImpactAnalysisResponse) GetGainedAccess() []int32 {
	if o == nil || IsNil(o.GainedAccess) {
		var ret []int32
		return ret
	}
	return o.GainedAccess
}

// GetGainedAccessOk returns a tuple with the GainedAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImpactAnalysisResponse) GetGainedAccessOk() ([]int32, bool) {
	if o == nil || IsNil(o.GainedAccess) {
		return nil, false
	}
	return o.GainedAccess, true
}

// HasGainedAccess returns a boolean if a field has been set.
func (o *ImpactAnalysisResponse) HasGainedAccess() bool {
	if o != nil && !IsNil(o.GainedAccess) {
		return true
	}

	return false
}

// SetGainedAccess gets a reference to the given []int32 and assigns it to the GainedAccess field.
func (o *ImpactAnalysisResponse) SetGainedAccess(v []int32) {
	o.GainedAccess = v
}

// GetLostAccess returns the LostAccess field value if set, zero value otherwise.
func (o *ImpactAnalysisResponse) GetLostAccess() []int32 {
	if o == nil || IsNil(o.LostAccess) {
		var ret []int32
		return ret
	}
	return o.LostAccess
}

// GetLostAccessOk returns a tuple with the LostAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImpactAnalysisResponse) GetLostAccessOk() ([]int32, bool) {
	if o == nil || IsNil(o.LostAccess) {
		return nil, false
	}
	return o.LostAccess, true
}

// HasLostAccess returns a boolean if a field has been set.
func (o *ImpactAnalysisResponse) HasLostAccess() bool {
	if o != nil && !IsNil(o.LostAccess) {
		return true
	}

	return false
}

// SetLostAccess gets a reference to the given []int32 and assigns it to the LostAccess field.
func (o *ImpactAnalysisResponse) SetLostAccess(v []int32) {
	o.LostAccess = v
}

func (o ImpactAnalysisResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImpactAnalysisResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GainedAccess) {
		toSerialize["gained_access"] = o.GainedAccess
	}
	if !IsNil(o.LostAccess) {
		toSerialize["lost_access"] = o.LostAccess
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ImpactAnalysisResponse) UnmarshalJSON(data []byte) (err error) {
	varImpactAnalysisResponse := _ImpactAnalysisResponse{}

	err = json.Unmarshal(data, &varImpactAnalysisResponse)

	if err != nil {
		return err
	}

	*o = ImpactAnalysisResponse(varImpactAnalysisResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "gained_access")
		delete(additionalProperties, "lost_access")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableImpactAnalysisResponse struct {
	value *ImpactAnalysisResponse
	isSet bool
}

func (v NullableImpactAnalysisResponse) Get() *ImpactAnalysisResponse {
	return v.value
}

func (v *NullableImpactAnalysisResponse) Set(val *ImpactAnalysisResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableImpactAnalysisResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableImpactAnalysisResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImpactAnalysisResponse(val *ImpactAnalysisResponse) *NullableImpactAnalysisResponse {
	return &NullableImpactAnalysisResponse{value: val, isSet: true}
}

func (v NullableImpactAnalysisResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImpactAnalysisResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


