/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"fmt"
)

// checks if the PolicySimulationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicySimulationResponse{}

// PolicySimulationResponse struct for PolicySimulationResponse
type PolicySimulationResponse struct {
	DecisionBefore map[string]interface{} `json:"decision_before"`
	DecisionAfter map[string]interface{} `json:"decision_after"`
	AdditionalProperties map[string]interface{}
}

type _PolicySimulationResponse PolicySimulationResponse

// NewPolicySimulationResponse instantiates a new PolicySimulationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicySimulationResponse(decisionBefore map[string]interface{}, decisionAfter map[string]interface{}) *PolicySimulationResponse {
	this := PolicySimulationResponse{}
	this.DecisionBefore = decisionBefore
	this.DecisionAfter = decisionAfter
	return &this
}

// NewPolicySimulationResponseWithDefaults instantiates a new PolicySimulationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicySimulationResponseWithDefaults() *PolicySimulationResponse {
	this := PolicySimulationResponse{}
	return &this
}

// GetDecisionBefore returns the DecisionBefore field value
func (o *PolicySimulationResponse) GetDecisionBefore() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.DecisionBefore
}

// GetDecisionBeforeOk returns a tuple with the DecisionBefore field value
// and a boolean to check if the value has been set.
func (o *PolicySimulationResponse) GetDecisionBeforeOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.DecisionBefore, true
}

// SetDecisionBefore sets field value
func (o *PolicySimulationResponse) SetDecisionBefore(v map[string]interface{}) {
	o.DecisionBefore = v
}

// GetDecisionAfter returns the DecisionAfter field value
func (o *PolicySimulationResponse) GetDecisionAfter() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.DecisionAfter
}

// GetDecisionAfterOk returns a tuple with the DecisionAfter field value
// and a boolean to check if the value has been set.
func (o *PolicySimulationResponse) GetDecisionAfterOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.DecisionAfter, true
}

// SetDecisionAfter sets field value
func (o *PolicySimulationResponse) SetDecisionAfter(v map[string]interface{}) {
	o.DecisionAfter = v
}

func (o PolicySimulationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicySimulationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["decision_before"] = o.DecisionBefore
	toSerialize["decision_after"] = o.DecisionAfter

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PolicySimulationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"decision_before",
		"decision_after",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicySimulationResponse := _PolicySimulationResponse{}

	err = json.Unmarshal(data, &varPolicySimulationResponse)

	if err != nil {
		return err
	}

	*o = PolicySimulationResponse(varPolicySimulationResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "decision_before")
		delete(additionalProperties, "decision_after")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePolicySimulationResponse struct {
	value *PolicySimulationResponse
	isSet bool
}

func (v NullablePolicySimulationResponse) Get() *PolicySimulationResponse {
	return v.value
}

func (v *NullablePolicySimulationResponse) Set(val *PolicySimulationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicySimulationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicySimulationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicySimulationResponse(val *PolicySimulationResponse) *NullablePolicySimulationResponse {
	return &NullablePolicySimulationResponse{value: val, isSet: true}
}

func (v NullablePolicySimulationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicySimulationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


