/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RoleCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleCreate{}

// RoleCreate struct for RoleCreate
type RoleCreate struct {
	Name string `json:"name"`
}

type _RoleCreate RoleCreate

// NewRoleCreate instantiates a new RoleCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleCreate(name string) *RoleCreate {
	this := RoleCreate{}
	this.Name = name
	return &this
}

// NewRoleCreateWithDefaults instantiates a new RoleCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleCreateWithDefaults() *RoleCreate {
	this := RoleCreate{}
	return &this
}

// GetName returns the Name field value
func (o *RoleCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RoleCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RoleCreate) SetName(v string) {
	o.Name = v
}

func (o RoleCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *RoleCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoleCreate := _RoleCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoleCreate)

	if err != nil {
		return err
	}

	*o = RoleCreate(varRoleCreate)

	return err
}

type NullableRoleCreate struct {
	value *RoleCreate
	isSet bool
}

func (v NullableRoleCreate) Get() *RoleCreate {
	return v.value
}

func (v *NullableRoleCreate) Set(val *RoleCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleCreate(val *RoleCreate) *NullableRoleCreate {
	return &NullableRoleCreate{value: val, isSet: true}
}

func (v NullableRoleCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


