/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminLoginResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminLoginResponse{}

// AdminLoginResponse struct for AdminLoginResponse
type AdminLoginResponse struct {
	AccessToken string `json:"access_token"`
	TokenType *string `json:"token_type,omitempty"`
	ExpiresIn int32 `json:"expires_in"`
	Role *string `json:"role,omitempty"`
	TenantKey string `json:"tenant_key"`
	AdditionalProperties map[string]interface{}
}

type _AdminLoginResponse AdminLoginResponse

// NewAdminLoginResponse instantiates a new AdminLoginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminLoginResponse(accessToken string, expiresIn int32, tenantKey string) *AdminLoginResponse {
	this := AdminLoginResponse{}
	this.AccessToken = accessToken
	var tokenType string = "bearer"
	this.TokenType = &tokenType
	this.ExpiresIn = expiresIn
	var role string = "admin"
	this.Role = &role
	this.TenantKey = tenantKey
	return &this
}

// NewAdminLoginResponseWithDefaults instantiates a new AdminLoginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminLoginResponseWithDefaults() *AdminLoginResponse {
	this := AdminLoginResponse{}
	var tokenType string = "bearer"
	this.TokenType = &tokenType
	var role string = "admin"
	this.Role = &role
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *AdminLoginResponse) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *AdminLoginResponse) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *AdminLoginResponse) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetTokenType returns the TokenType field value if set, zero value otherwise.
func (o *AdminLoginResponse) GetTokenType() string {
	if o == nil || IsNil(o.TokenType) {
		var ret string
		return ret
	}
	return *o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminLoginResponse) GetTokenTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TokenType) {
		return nil, false
	}
	return o.TokenType, true
}

// HasTokenType returns a boolean if a field has been set.
func (o *AdminLoginResponse) HasTokenType() bool {
	if o != nil && !IsNil(o.TokenType) {
		return true
	}

	return false
}

// SetTokenType gets a reference to the given string and assigns it to the TokenType field.
func (o *AdminLoginResponse) SetTokenType(v string) {
	o.TokenType = &v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *AdminLoginResponse) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *AdminLoginResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *AdminLoginResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *AdminLoginResponse) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminLoginResponse) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *AdminLoginResponse) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *AdminLoginResponse) SetRole(v string) {
	o.Role = &v
}

// GetTenantKey returns the TenantKey field value
func (o *AdminLoginResponse) GetTenantKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantKey
}

// GetTenantKeyOk returns a tuple with the TenantKey field value
// and a boolean to check if the value has been set.
func (o *AdminLoginResponse) GetTenantKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantKey, true
}

// SetTenantKey sets field value
func (o *AdminLoginResponse) SetTenantKey(v string) {
	o.TenantKey = v
}

func (o AdminLoginResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminLoginResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	if !IsNil(o.TokenType) {
		toSerialize["token_type"] = o.TokenType
	}
	toSerialize["expires_in"] = o.ExpiresIn
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	toSerialize["tenant_key"] = o.TenantKey

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminLoginResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"expires_in",
		"tenant_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminLoginResponse := _AdminLoginResponse{}

	err = json.Unmarshal(data, &varAdminLoginResponse)

	if err != nil {
		return err
	}

	*o = AdminLoginResponse(varAdminLoginResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "access_token")
		delete(additionalProperties, "token_type")
		delete(additionalProperties, "expires_in")
		delete(additionalProperties, "role")
		delete(additionalProperties, "tenant_key")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminLoginResponse struct {
	value *AdminLoginResponse
	isSet bool
}

func (v NullableAdminLoginResponse) Get() *AdminLoginResponse {
	return v.value
}

func (v *NullableAdminLoginResponse) Set(val *AdminLoginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminLoginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminLoginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminLoginResponse(val *AdminLoginResponse) *NullableAdminLoginResponse {
	return &NullableAdminLoginResponse{value: val, isSet: true}
}

func (v NullableAdminLoginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminLoginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


