/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"fmt"
)

// checks if the PolicyCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyCreate{}

// PolicyCreate struct for PolicyCreate
type PolicyCreate struct {
	Action string `json:"action"`
	Effect *string `json:"effect,omitempty"`
	Priority *int32 `json:"priority,omitempty"`
	State *string `json:"state,omitempty"`
	Conditions map[string]interface{} `json:"conditions,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PolicyCreate PolicyCreate

// NewPolicyCreate instantiates a new PolicyCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyCreate(action string) *PolicyCreate {
	this := PolicyCreate{}
	this.Action = action
	var effect string = "allow"
	this.Effect = &effect
	var priority int32 = 100
	this.Priority = &priority
	var state string = "active"
	this.State = &state
	return &this
}

// NewPolicyCreateWithDefaults instantiates a new PolicyCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyCreateWithDefaults() *PolicyCreate {
	this := PolicyCreate{}
	var effect string = "allow"
	this.Effect = &effect
	var priority int32 = 100
	this.Priority = &priority
	var state string = "active"
	this.State = &state
	return &this
}

// GetAction returns the Action field value
func (o *PolicyCreate) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *PolicyCreate) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *PolicyCreate) SetAction(v string) {
	o.Action = v
}

// GetEffect returns the Effect field value if set, zero value otherwise.
func (o *PolicyCreate) GetEffect() string {
	if o == nil || IsNil(o.Effect) {
		var ret string
		return ret
	}
	return *o.Effect
}

// GetEffectOk returns a tuple with the Effect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyCreate) GetEffectOk() (*string, bool) {
	if o == nil || IsNil(o.Effect) {
		return nil, false
	}
	return o.Effect, true
}

// HasEffect returns a boolean if a field has been set.
func (o *PolicyCreate) HasEffect() bool {
	if o != nil && !IsNil(o.Effect) {
		return true
	}

	return false
}

// SetEffect gets a reference to the given string and assigns it to the Effect field.
func (o *PolicyCreate) SetEffect(v string) {
	o.Effect = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *PolicyCreate) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyCreate) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *PolicyCreate) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *PolicyCreate) SetPriority(v int32) {
	o.Priority = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *PolicyCreate) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyCreate) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *PolicyCreate) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *PolicyCreate) SetState(v string) {
	o.State = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *PolicyCreate) GetConditions() map[string]interface{} {
	if o == nil || IsNil(o.Conditions) {
		var ret map[string]interface{}
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyCreate) GetConditionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Conditions) {
		return map[string]interface{}{}, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *PolicyCreate) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given map[string]interface{} and assigns it to the Conditions field.
func (o *PolicyCreate) SetConditions(v map[string]interface{}) {
	o.Conditions = v
}

func (o PolicyCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.Effect) {
		toSerialize["effect"] = o.Effect
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PolicyCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicyCreate := _PolicyCreate{}

	err = json.Unmarshal(data, &varPolicyCreate)

	if err != nil {
		return err
	}

	*o = PolicyCreate(varPolicyCreate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "action")
		delete(additionalProperties, "effect")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "state")
		delete(additionalProperties, "conditions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePolicyCreate struct {
	value *PolicyCreate
	isSet bool
}

func (v NullablePolicyCreate) Get() *PolicyCreate {
	return v.value
}

func (v *NullablePolicyCreate) Set(val *PolicyCreate) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyCreate) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyCreate(val *PolicyCreate) *NullablePolicyCreate {
	return &NullablePolicyCreate{value: val, isSet: true}
}

func (v NullablePolicyCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


