/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SuccessResponseDictStrUnionIntStr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessResponseDictStrUnionIntStr{}

// SuccessResponseDictStrUnionIntStr struct for SuccessResponseDictStrUnionIntStr
type SuccessResponseDictStrUnionIntStr struct {
	Data map[string]DataValue `json:"data"`
	Meta *MetaBody `json:"meta,omitempty"`
	Error *interface{} `json:"error,omitempty"`
}

type _SuccessResponseDictStrUnionIntStr SuccessResponseDictStrUnionIntStr

// NewSuccessResponseDictStrUnionIntStr instantiates a new SuccessResponseDictStrUnionIntStr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessResponseDictStrUnionIntStr(data map[string]DataValue) *SuccessResponseDictStrUnionIntStr {
	this := SuccessResponseDictStrUnionIntStr{}
	this.Data = data
	return &this
}

// NewSuccessResponseDictStrUnionIntStrWithDefaults instantiates a new SuccessResponseDictStrUnionIntStr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessResponseDictStrUnionIntStrWithDefaults() *SuccessResponseDictStrUnionIntStr {
	this := SuccessResponseDictStrUnionIntStr{}
	return &this
}

// GetData returns the Data field value
func (o *SuccessResponseDictStrUnionIntStr) GetData() map[string]DataValue {
	if o == nil {
		var ret map[string]DataValue
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SuccessResponseDictStrUnionIntStr) GetDataOk() (map[string]DataValue, bool) {
	if o == nil {
		return map[string]DataValue{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SuccessResponseDictStrUnionIntStr) SetData(v map[string]DataValue) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SuccessResponseDictStrUnionIntStr) GetMeta() MetaBody {
	if o == nil || IsNil(o.Meta) {
		var ret MetaBody
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseDictStrUnionIntStr) GetMetaOk() (*MetaBody, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SuccessResponseDictStrUnionIntStr) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaBody and assigns it to the Meta field.
func (o *SuccessResponseDictStrUnionIntStr) SetMeta(v MetaBody) {
	o.Meta = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SuccessResponseDictStrUnionIntStr) GetError() interface{} {
	if o == nil || IsNil(o.Error) {
		var ret interface{}
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseDictStrUnionIntStr) GetErrorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SuccessResponseDictStrUnionIntStr) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given interface{} and assigns it to the Error field.
func (o *SuccessResponseDictStrUnionIntStr) SetError(v interface{}) {
	o.Error = &v
}

func (o SuccessResponseDictStrUnionIntStr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessResponseDictStrUnionIntStr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *SuccessResponseDictStrUnionIntStr) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessResponseDictStrUnionIntStr := _SuccessResponseDictStrUnionIntStr{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSuccessResponseDictStrUnionIntStr)

	if err != nil {
		return err
	}

	*o = SuccessResponseDictStrUnionIntStr(varSuccessResponseDictStrUnionIntStr)

	return err
}

type NullableSuccessResponseDictStrUnionIntStr struct {
	value *SuccessResponseDictStrUnionIntStr
	isSet bool
}

func (v NullableSuccessResponseDictStrUnionIntStr) Get() *SuccessResponseDictStrUnionIntStr {
	return v.value
}

func (v *NullableSuccessResponseDictStrUnionIntStr) Set(val *SuccessResponseDictStrUnionIntStr) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessResponseDictStrUnionIntStr) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessResponseDictStrUnionIntStr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessResponseDictStrUnionIntStr(val *SuccessResponseDictStrUnionIntStr) *NullableSuccessResponseDictStrUnionIntStr {
	return &NullableSuccessResponseDictStrUnionIntStr{value: val, isSet: true}
}

func (v NullableSuccessResponseDictStrUnionIntStr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessResponseDictStrUnionIntStr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


