/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"fmt"
)

// checks if the SuccessResponseDictStrObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessResponseDictStrObject{}

// SuccessResponseDictStrObject struct for SuccessResponseDictStrObject
type SuccessResponseDictStrObject struct {
	Data map[string]interface{} `json:"data"`
	Meta *MetaBody `json:"meta,omitempty"`
	Error *interface{} `json:"error,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SuccessResponseDictStrObject SuccessResponseDictStrObject

// NewSuccessResponseDictStrObject instantiates a new SuccessResponseDictStrObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessResponseDictStrObject(data map[string]interface{}) *SuccessResponseDictStrObject {
	this := SuccessResponseDictStrObject{}
	this.Data = data
	return &this
}

// NewSuccessResponseDictStrObjectWithDefaults instantiates a new SuccessResponseDictStrObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessResponseDictStrObjectWithDefaults() *SuccessResponseDictStrObject {
	this := SuccessResponseDictStrObject{}
	return &this
}

// GetData returns the Data field value
func (o *SuccessResponseDictStrObject) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SuccessResponseDictStrObject) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SuccessResponseDictStrObject) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SuccessResponseDictStrObject) GetMeta() MetaBody {
	if o == nil || IsNil(o.Meta) {
		var ret MetaBody
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseDictStrObject) GetMetaOk() (*MetaBody, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SuccessResponseDictStrObject) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaBody and assigns it to the Meta field.
func (o *SuccessResponseDictStrObject) SetMeta(v MetaBody) {
	o.Meta = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SuccessResponseDictStrObject) GetError() interface{} {
	if o == nil || IsNil(o.Error) {
		var ret interface{}
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseDictStrObject) GetErrorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SuccessResponseDictStrObject) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given interface{} and assigns it to the Error field.
func (o *SuccessResponseDictStrObject) SetError(v interface{}) {
	o.Error = &v
}

func (o SuccessResponseDictStrObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessResponseDictStrObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SuccessResponseDictStrObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessResponseDictStrObject := _SuccessResponseDictStrObject{}

	err = json.Unmarshal(data, &varSuccessResponseDictStrObject)

	if err != nil {
		return err
	}

	*o = SuccessResponseDictStrObject(varSuccessResponseDictStrObject)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "meta")
		delete(additionalProperties, "error")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSuccessResponseDictStrObject struct {
	value *SuccessResponseDictStrObject
	isSet bool
}

func (v NullableSuccessResponseDictStrObject) Get() *SuccessResponseDictStrObject {
	return v.value
}

func (v *NullableSuccessResponseDictStrObject) Set(val *SuccessResponseDictStrObject) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessResponseDictStrObject) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessResponseDictStrObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessResponseDictStrObject(val *SuccessResponseDictStrObject) *NullableSuccessResponseDictStrObject {
	return &NullableSuccessResponseDictStrObject{value: val, isSet: true}
}

func (v NullableSuccessResponseDictStrObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessResponseDictStrObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


