/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PermissionCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionCreate{}

// PermissionCreate struct for PermissionCreate
type PermissionCreate struct {
	Action string `json:"action"`
}

type _PermissionCreate PermissionCreate

// NewPermissionCreate instantiates a new PermissionCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionCreate(action string) *PermissionCreate {
	this := PermissionCreate{}
	this.Action = action
	return &this
}

// NewPermissionCreateWithDefaults instantiates a new PermissionCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionCreateWithDefaults() *PermissionCreate {
	this := PermissionCreate{}
	return &this
}

// GetAction returns the Action field value
func (o *PermissionCreate) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *PermissionCreate) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *PermissionCreate) SetAction(v string) {
	o.Action = v
}

func (o PermissionCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *PermissionCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPermissionCreate := _PermissionCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPermissionCreate)

	if err != nil {
		return err
	}

	*o = PermissionCreate(varPermissionCreate)

	return err
}

type NullablePermissionCreate struct {
	value *PermissionCreate
	isSet bool
}

func (v NullablePermissionCreate) Get() *PermissionCreate {
	return v.value
}

func (v *NullablePermissionCreate) Set(val *PermissionCreate) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionCreate) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionCreate(val *PermissionCreate) *NullablePermissionCreate {
	return &NullablePermissionCreate{value: val, isSet: true}
}

func (v NullablePermissionCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


