/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
)

// checks if the PolicySimulationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicySimulationRequest{}

// PolicySimulationRequest struct for PolicySimulationRequest
type PolicySimulationRequest struct {
	Simulate *PolicySimulationInput `json:"simulate,omitempty"`
	Request map[string]interface{} `json:"request,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PolicySimulationRequest PolicySimulationRequest

// NewPolicySimulationRequest instantiates a new PolicySimulationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicySimulationRequest() *PolicySimulationRequest {
	this := PolicySimulationRequest{}
	return &this
}

// NewPolicySimulationRequestWithDefaults instantiates a new PolicySimulationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicySimulationRequestWithDefaults() *PolicySimulationRequest {
	this := PolicySimulationRequest{}
	return &this
}

// GetSimulate returns the Simulate field value if set, zero value otherwise.
func (o *PolicySimulationRequest) GetSimulate() PolicySimulationInput {
	if o == nil || IsNil(o.Simulate) {
		var ret PolicySimulationInput
		return ret
	}
	return *o.Simulate
}

// GetSimulateOk returns a tuple with the Simulate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicySimulationRequest) GetSimulateOk() (*PolicySimulationInput, bool) {
	if o == nil || IsNil(o.Simulate) {
		return nil, false
	}
	return o.Simulate, true
}

// HasSimulate returns a boolean if a field has been set.
func (o *PolicySimulationRequest) HasSimulate() bool {
	if o != nil && !IsNil(o.Simulate) {
		return true
	}

	return false
}

// SetSimulate gets a reference to the given PolicySimulationInput and assigns it to the Simulate field.
func (o *PolicySimulationRequest) SetSimulate(v PolicySimulationInput) {
	o.Simulate = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *PolicySimulationRequest) GetRequest() map[string]interface{} {
	if o == nil || IsNil(o.Request) {
		var ret map[string]interface{}
		return ret
	}
	return o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicySimulationRequest) GetRequestOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Request) {
		return map[string]interface{}{}, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *PolicySimulationRequest) HasRequest() bool {
	if o != nil && !IsNil(o.Request) {
		return true
	}

	return false
}

// SetRequest gets a reference to the given map[string]interface{} and assigns it to the Request field.
func (o *PolicySimulationRequest) SetRequest(v map[string]interface{}) {
	o.Request = v
}

func (o PolicySimulationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicySimulationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Simulate) {
		toSerialize["simulate"] = o.Simulate
	}
	if !IsNil(o.Request) {
		toSerialize["request"] = o.Request
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PolicySimulationRequest) UnmarshalJSON(data []byte) (err error) {
	varPolicySimulationRequest := _PolicySimulationRequest{}

	err = json.Unmarshal(data, &varPolicySimulationRequest)

	if err != nil {
		return err
	}

	*o = PolicySimulationRequest(varPolicySimulationRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "simulate")
		delete(additionalProperties, "request")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePolicySimulationRequest struct {
	value *PolicySimulationRequest
	isSet bool
}

func (v NullablePolicySimulationRequest) Get() *PolicySimulationRequest {
	return v.value
}

func (v *NullablePolicySimulationRequest) Set(val *PolicySimulationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicySimulationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicySimulationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicySimulationRequest(val *PolicySimulationRequest) *NullablePolicySimulationRequest {
	return &NullablePolicySimulationRequest{value: val, isSet: true}
}

func (v NullablePolicySimulationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicySimulationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


