/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SuccessResponseAdminLoginResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessResponseAdminLoginResponse{}

// SuccessResponseAdminLoginResponse struct for SuccessResponseAdminLoginResponse
type SuccessResponseAdminLoginResponse struct {
	Data AdminLoginResponse `json:"data"`
	Meta *MetaBody `json:"meta,omitempty"`
	Error *nil `json:"error,omitempty"`
}

type _SuccessResponseAdminLoginResponse SuccessResponseAdminLoginResponse

// NewSuccessResponseAdminLoginResponse instantiates a new SuccessResponseAdminLoginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessResponseAdminLoginResponse(data AdminLoginResponse) *SuccessResponseAdminLoginResponse {
	this := SuccessResponseAdminLoginResponse{}
	this.Data = data
	return &this
}

// NewSuccessResponseAdminLoginResponseWithDefaults instantiates a new SuccessResponseAdminLoginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessResponseAdminLoginResponseWithDefaults() *SuccessResponseAdminLoginResponse {
	this := SuccessResponseAdminLoginResponse{}
	return &this
}

// GetData returns the Data field value
func (o *SuccessResponseAdminLoginResponse) GetData() AdminLoginResponse {
	if o == nil {
		var ret AdminLoginResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SuccessResponseAdminLoginResponse) GetDataOk() (*AdminLoginResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SuccessResponseAdminLoginResponse) SetData(v AdminLoginResponse) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SuccessResponseAdminLoginResponse) GetMeta() MetaBody {
	if o == nil || IsNil(o.Meta) {
		var ret MetaBody
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseAdminLoginResponse) GetMetaOk() (*MetaBody, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SuccessResponseAdminLoginResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaBody and assigns it to the Meta field.
func (o *SuccessResponseAdminLoginResponse) SetMeta(v MetaBody) {
	o.Meta = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SuccessResponseAdminLoginResponse) GetError() nil {
	if o == nil || IsNil(o.Error) {
		var ret nil
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseAdminLoginResponse) GetErrorOk() (*nil, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SuccessResponseAdminLoginResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given nil and assigns it to the Error field.
func (o *SuccessResponseAdminLoginResponse) SetError(v nil) {
	o.Error = &v
}

func (o SuccessResponseAdminLoginResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessResponseAdminLoginResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *SuccessResponseAdminLoginResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessResponseAdminLoginResponse := _SuccessResponseAdminLoginResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSuccessResponseAdminLoginResponse)

	if err != nil {
		return err
	}

	*o = SuccessResponseAdminLoginResponse(varSuccessResponseAdminLoginResponse)

	return err
}

type NullableSuccessResponseAdminLoginResponse struct {
	value *SuccessResponseAdminLoginResponse
	isSet bool
}

func (v NullableSuccessResponseAdminLoginResponse) Get() *SuccessResponseAdminLoginResponse {
	return v.value
}

func (v *NullableSuccessResponseAdminLoginResponse) Set(val *SuccessResponseAdminLoginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessResponseAdminLoginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessResponseAdminLoginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessResponseAdminLoginResponse(val *SuccessResponseAdminLoginResponse) *NullableSuccessResponseAdminLoginResponse {
	return &NullableSuccessResponseAdminLoginResponse{value: val, isSet: true}
}

func (v NullableSuccessResponseAdminLoginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessResponseAdminLoginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


