/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"fmt"
)

// checks if the RelationshipCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RelationshipCreate{}

// RelationshipCreate struct for RelationshipCreate
type RelationshipCreate struct {
	SubjectType string `json:"subject_type"`
	SubjectId string `json:"subject_id"`
	Relation string `json:"relation"`
	ObjectType string `json:"object_type"`
	ObjectId string `json:"object_id"`
	AdditionalProperties map[string]interface{}
}

type _RelationshipCreate RelationshipCreate

// NewRelationshipCreate instantiates a new RelationshipCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationshipCreate(subjectType string, subjectId string, relation string, objectType string, objectId string) *RelationshipCreate {
	this := RelationshipCreate{}
	this.SubjectType = subjectType
	this.SubjectId = subjectId
	this.Relation = relation
	this.ObjectType = objectType
	this.ObjectId = objectId
	return &this
}

// NewRelationshipCreateWithDefaults instantiates a new RelationshipCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationshipCreateWithDefaults() *RelationshipCreate {
	this := RelationshipCreate{}
	return &this
}

// GetSubjectType returns the SubjectType field value
func (o *RelationshipCreate) GetSubjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectType
}

// GetSubjectTypeOk returns a tuple with the SubjectType field value
// and a boolean to check if the value has been set.
func (o *RelationshipCreate) GetSubjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectType, true
}

// SetSubjectType sets field value
func (o *RelationshipCreate) SetSubjectType(v string) {
	o.SubjectType = v
}

// GetSubjectId returns the SubjectId field value
func (o *RelationshipCreate) GetSubjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectId
}

// GetSubjectIdOk returns a tuple with the SubjectId field value
// and a boolean to check if the value has been set.
func (o *RelationshipCreate) GetSubjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectId, true
}

// SetSubjectId sets field value
func (o *RelationshipCreate) SetSubjectId(v string) {
	o.SubjectId = v
}

// GetRelation returns the Relation field value
func (o *RelationshipCreate) GetRelation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Relation
}

// GetRelationOk returns a tuple with the Relation field value
// and a boolean to check if the value has been set.
func (o *RelationshipCreate) GetRelationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relation, true
}

// SetRelation sets field value
func (o *RelationshipCreate) SetRelation(v string) {
	o.Relation = v
}

// GetObjectType returns the ObjectType field value
func (o *RelationshipCreate) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *RelationshipCreate) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *RelationshipCreate) SetObjectType(v string) {
	o.ObjectType = v
}

// GetObjectId returns the ObjectId field value
func (o *RelationshipCreate) GetObjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectId
}

// GetObjectIdOk returns a tuple with the ObjectId field value
// and a boolean to check if the value has been set.
func (o *RelationshipCreate) GetObjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectId, true
}

// SetObjectId sets field value
func (o *RelationshipCreate) SetObjectId(v string) {
	o.ObjectId = v
}

func (o RelationshipCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RelationshipCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subject_type"] = o.SubjectType
	toSerialize["subject_id"] = o.SubjectId
	toSerialize["relation"] = o.Relation
	toSerialize["object_type"] = o.ObjectType
	toSerialize["object_id"] = o.ObjectId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RelationshipCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subject_type",
		"subject_id",
		"relation",
		"object_type",
		"object_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRelationshipCreate := _RelationshipCreate{}

	err = json.Unmarshal(data, &varRelationshipCreate)

	if err != nil {
		return err
	}

	*o = RelationshipCreate(varRelationshipCreate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subject_type")
		delete(additionalProperties, "subject_id")
		delete(additionalProperties, "relation")
		delete(additionalProperties, "object_type")
		delete(additionalProperties, "object_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRelationshipCreate struct {
	value *RelationshipCreate
	isSet bool
}

func (v NullableRelationshipCreate) Get() *RelationshipCreate {
	return v.value
}

func (v *NullableRelationshipCreate) Set(val *RelationshipCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationshipCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationshipCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationshipCreate(val *RelationshipCreate) *NullableRelationshipCreate {
	return &NullableRelationshipCreate{value: val, isSet: true}
}

func (v NullableRelationshipCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationshipCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


