/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"fmt"
)

// checks if the SimulationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SimulationResponse{}

// SimulationResponse struct for SimulationResponse
type SimulationResponse struct {
	Decision string `json:"decision"`
	MatchedPolicies []string `json:"matched_policies"`
	Reason NullableString `json:"reason,omitempty"`
	PolicyId NullableString `json:"policy_id,omitempty"`
	ExplainTrace []map[string]interface{} `json:"explain_trace,omitempty"`
	FailedConditions []string `json:"failed_conditions,omitempty"`
	Revision NullableInt32 `json:"revision,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SimulationResponse SimulationResponse

// NewSimulationResponse instantiates a new SimulationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSimulationResponse(decision string, matchedPolicies []string) *SimulationResponse {
	this := SimulationResponse{}
	this.Decision = decision
	this.MatchedPolicies = matchedPolicies
	return &this
}

// NewSimulationResponseWithDefaults instantiates a new SimulationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSimulationResponseWithDefaults() *SimulationResponse {
	this := SimulationResponse{}
	return &this
}

// GetDecision returns the Decision field value
func (o *SimulationResponse) GetDecision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Decision
}

// GetDecisionOk returns a tuple with the Decision field value
// and a boolean to check if the value has been set.
func (o *SimulationResponse) GetDecisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decision, true
}

// SetDecision sets field value
func (o *SimulationResponse) SetDecision(v string) {
	o.Decision = v
}

// GetMatchedPolicies returns the MatchedPolicies field value
func (o *SimulationResponse) GetMatchedPolicies() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MatchedPolicies
}

// GetMatchedPoliciesOk returns a tuple with the MatchedPolicies field value
// and a boolean to check if the value has been set.
func (o *SimulationResponse) GetMatchedPoliciesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MatchedPolicies, true
}

// SetMatchedPolicies sets field value
func (o *SimulationResponse) SetMatchedPolicies(v []string) {
	o.MatchedPolicies = v
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SimulationResponse) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SimulationResponse) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *SimulationResponse) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *SimulationResponse) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *SimulationResponse) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *SimulationResponse) UnsetReason() {
	o.Reason.Unset()
}

// GetPolicyId returns the PolicyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SimulationResponse) GetPolicyId() string {
	if o == nil || IsNil(o.PolicyId.Get()) {
		var ret string
		return ret
	}
	return *o.PolicyId.Get()
}

// GetPolicyIdOk returns a tuple with the PolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SimulationResponse) GetPolicyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyId.Get(), o.PolicyId.IsSet()
}

// HasPolicyId returns a boolean if a field has been set.
func (o *SimulationResponse) HasPolicyId() bool {
	if o != nil && o.PolicyId.IsSet() {
		return true
	}

	return false
}

// SetPolicyId gets a reference to the given NullableString and assigns it to the PolicyId field.
func (o *SimulationResponse) SetPolicyId(v string) {
	o.PolicyId.Set(&v)
}
// SetPolicyIdNil sets the value for PolicyId to be an explicit nil
func (o *SimulationResponse) SetPolicyIdNil() {
	o.PolicyId.Set(nil)
}

// UnsetPolicyId ensures that no value is present for PolicyId, not even an explicit nil
func (o *SimulationResponse) UnsetPolicyId() {
	o.PolicyId.Unset()
}

// GetExplainTrace returns the ExplainTrace field value if set, zero value otherwise.
func (o *SimulationResponse) GetExplainTrace() []map[string]interface{} {
	if o == nil || IsNil(o.ExplainTrace) {
		var ret []map[string]interface{}
		return ret
	}
	return o.ExplainTrace
}

// GetExplainTraceOk returns a tuple with the ExplainTrace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimulationResponse) GetExplainTraceOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExplainTrace) {
		return nil, false
	}
	return o.ExplainTrace, true
}

// HasExplainTrace returns a boolean if a field has been set.
func (o *SimulationResponse) HasExplainTrace() bool {
	if o != nil && !IsNil(o.ExplainTrace) {
		return true
	}

	return false
}

// SetExplainTrace gets a reference to the given []map[string]interface{} and assigns it to the ExplainTrace field.
func (o *SimulationResponse) SetExplainTrace(v []map[string]interface{}) {
	o.ExplainTrace = v
}

// GetFailedConditions returns the FailedConditions field value if set, zero value otherwise.
func (o *SimulationResponse) GetFailedConditions() []string {
	if o == nil || IsNil(o.FailedConditions) {
		var ret []string
		return ret
	}
	return o.FailedConditions
}

// GetFailedConditionsOk returns a tuple with the FailedConditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimulationResponse) GetFailedConditionsOk() ([]string, bool) {
	if o == nil || IsNil(o.FailedConditions) {
		return nil, false
	}
	return o.FailedConditions, true
}

// HasFailedConditions returns a boolean if a field has been set.
func (o *SimulationResponse) HasFailedConditions() bool {
	if o != nil && !IsNil(o.FailedConditions) {
		return true
	}

	return false
}

// SetFailedConditions gets a reference to the given []string and assigns it to the FailedConditions field.
func (o *SimulationResponse) SetFailedConditions(v []string) {
	o.FailedConditions = v
}

// GetRevision returns the Revision field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SimulationResponse) GetRevision() int32 {
	if o == nil || IsNil(o.Revision.Get()) {
		var ret int32
		return ret
	}
	return *o.Revision.Get()
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SimulationResponse) GetRevisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Revision.Get(), o.Revision.IsSet()
}

// HasRevision returns a boolean if a field has been set.
func (o *SimulationResponse) HasRevision() bool {
	if o != nil && o.Revision.IsSet() {
		return true
	}

	return false
}

// SetRevision gets a reference to the given NullableInt32 and assigns it to the Revision field.
func (o *SimulationResponse) SetRevision(v int32) {
	o.Revision.Set(&v)
}
// SetRevisionNil sets the value for Revision to be an explicit nil
func (o *SimulationResponse) SetRevisionNil() {
	o.Revision.Set(nil)
}

// UnsetRevision ensures that no value is present for Revision, not even an explicit nil
func (o *SimulationResponse) UnsetRevision() {
	o.Revision.Unset()
}

func (o SimulationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SimulationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["decision"] = o.Decision
	toSerialize["matched_policies"] = o.MatchedPolicies
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	if o.PolicyId.IsSet() {
		toSerialize["policy_id"] = o.PolicyId.Get()
	}
	if !IsNil(o.ExplainTrace) {
		toSerialize["explain_trace"] = o.ExplainTrace
	}
	if !IsNil(o.FailedConditions) {
		toSerialize["failed_conditions"] = o.FailedConditions
	}
	if o.Revision.IsSet() {
		toSerialize["revision"] = o.Revision.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SimulationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"decision",
		"matched_policies",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSimulationResponse := _SimulationResponse{}

	err = json.Unmarshal(data, &varSimulationResponse)

	if err != nil {
		return err
	}

	*o = SimulationResponse(varSimulationResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "decision")
		delete(additionalProperties, "matched_policies")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "policy_id")
		delete(additionalProperties, "explain_trace")
		delete(additionalProperties, "failed_conditions")
		delete(additionalProperties, "revision")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSimulationResponse struct {
	value *SimulationResponse
	isSet bool
}

func (v NullableSimulationResponse) Get() *SimulationResponse {
	return v.value
}

func (v *NullableSimulationResponse) Set(val *SimulationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSimulationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSimulationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimulationResponse(val *SimulationResponse) *NullableSimulationResponse {
	return &NullableSimulationResponse{value: val, isSet: true}
}

func (v NullableSimulationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimulationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


