/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SuccessResponseRelationshipOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessResponseRelationshipOut{}

// SuccessResponseRelationshipOut struct for SuccessResponseRelationshipOut
type SuccessResponseRelationshipOut struct {
	Data RelationshipOut `json:"data"`
	Meta *MetaBody `json:"meta,omitempty"`
	Error *nil `json:"error,omitempty"`
}

type _SuccessResponseRelationshipOut SuccessResponseRelationshipOut

// NewSuccessResponseRelationshipOut instantiates a new SuccessResponseRelationshipOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessResponseRelationshipOut(data RelationshipOut) *SuccessResponseRelationshipOut {
	this := SuccessResponseRelationshipOut{}
	this.Data = data
	return &this
}

// NewSuccessResponseRelationshipOutWithDefaults instantiates a new SuccessResponseRelationshipOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessResponseRelationshipOutWithDefaults() *SuccessResponseRelationshipOut {
	this := SuccessResponseRelationshipOut{}
	return &this
}

// GetData returns the Data field value
func (o *SuccessResponseRelationshipOut) GetData() RelationshipOut {
	if o == nil {
		var ret RelationshipOut
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SuccessResponseRelationshipOut) GetDataOk() (*RelationshipOut, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SuccessResponseRelationshipOut) SetData(v RelationshipOut) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SuccessResponseRelationshipOut) GetMeta() MetaBody {
	if o == nil || IsNil(o.Meta) {
		var ret MetaBody
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseRelationshipOut) GetMetaOk() (*MetaBody, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SuccessResponseRelationshipOut) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaBody and assigns it to the Meta field.
func (o *SuccessResponseRelationshipOut) SetMeta(v MetaBody) {
	o.Meta = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SuccessResponseRelationshipOut) GetError() nil {
	if o == nil || IsNil(o.Error) {
		var ret nil
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseRelationshipOut) GetErrorOk() (*nil, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SuccessResponseRelationshipOut) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given nil and assigns it to the Error field.
func (o *SuccessResponseRelationshipOut) SetError(v nil) {
	o.Error = &v
}

func (o SuccessResponseRelationshipOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessResponseRelationshipOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *SuccessResponseRelationshipOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessResponseRelationshipOut := _SuccessResponseRelationshipOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSuccessResponseRelationshipOut)

	if err != nil {
		return err
	}

	*o = SuccessResponseRelationshipOut(varSuccessResponseRelationshipOut)

	return err
}

type NullableSuccessResponseRelationshipOut struct {
	value *SuccessResponseRelationshipOut
	isSet bool
}

func (v NullableSuccessResponseRelationshipOut) Get() *SuccessResponseRelationshipOut {
	return v.value
}

func (v *NullableSuccessResponseRelationshipOut) Set(val *SuccessResponseRelationshipOut) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessResponseRelationshipOut) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessResponseRelationshipOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessResponseRelationshipOut(val *SuccessResponseRelationshipOut) *NullableSuccessResponseRelationshipOut {
	return &NullableSuccessResponseRelationshipOut{value: val, isSet: true}
}

func (v NullableSuccessResponseRelationshipOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessResponseRelationshipOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


