/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"fmt"
)

// checks if the RoleOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleOut{}

// RoleOut struct for RoleOut
type RoleOut struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _RoleOut RoleOut

// NewRoleOut instantiates a new RoleOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleOut(id int32, name string) *RoleOut {
	this := RoleOut{}
	this.Id = id
	this.Name = name
	return &this
}

// NewRoleOutWithDefaults instantiates a new RoleOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleOutWithDefaults() *RoleOut {
	this := RoleOut{}
	return &this
}

// GetId returns the Id field value
func (o *RoleOut) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RoleOut) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RoleOut) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *RoleOut) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RoleOut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RoleOut) SetName(v string) {
	o.Name = v
}

func (o RoleOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RoleOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoleOut := _RoleOut{}

	err = json.Unmarshal(data, &varRoleOut)

	if err != nil {
		return err
	}

	*o = RoleOut(varRoleOut)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRoleOut struct {
	value *RoleOut
	isSet bool
}

func (v NullableRoleOut) Get() *RoleOut {
	return v.value
}

func (v *NullableRoleOut) Set(val *RoleOut) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleOut) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleOut(val *RoleOut) *NullableRoleOut {
	return &NullableRoleOut{value: val, isSet: true}
}

func (v NullableRoleOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


