/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SuccessResponseSimulationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessResponseSimulationResponse{}

// SuccessResponseSimulationResponse struct for SuccessResponseSimulationResponse
type SuccessResponseSimulationResponse struct {
	Data SimulationResponse `json:"data"`
	Meta *MetaBody `json:"meta,omitempty"`
	Error *nil `json:"error,omitempty"`
}

type _SuccessResponseSimulationResponse SuccessResponseSimulationResponse

// NewSuccessResponseSimulationResponse instantiates a new SuccessResponseSimulationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessResponseSimulationResponse(data SimulationResponse) *SuccessResponseSimulationResponse {
	this := SuccessResponseSimulationResponse{}
	this.Data = data
	return &this
}

// NewSuccessResponseSimulationResponseWithDefaults instantiates a new SuccessResponseSimulationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessResponseSimulationResponseWithDefaults() *SuccessResponseSimulationResponse {
	this := SuccessResponseSimulationResponse{}
	return &this
}

// GetData returns the Data field value
func (o *SuccessResponseSimulationResponse) GetData() SimulationResponse {
	if o == nil {
		var ret SimulationResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SuccessResponseSimulationResponse) GetDataOk() (*SimulationResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SuccessResponseSimulationResponse) SetData(v SimulationResponse) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SuccessResponseSimulationResponse) GetMeta() MetaBody {
	if o == nil || IsNil(o.Meta) {
		var ret MetaBody
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseSimulationResponse) GetMetaOk() (*MetaBody, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SuccessResponseSimulationResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaBody and assigns it to the Meta field.
func (o *SuccessResponseSimulationResponse) SetMeta(v MetaBody) {
	o.Meta = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SuccessResponseSimulationResponse) GetError() nil {
	if o == nil || IsNil(o.Error) {
		var ret nil
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseSimulationResponse) GetErrorOk() (*nil, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SuccessResponseSimulationResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given nil and assigns it to the Error field.
func (o *SuccessResponseSimulationResponse) SetError(v nil) {
	o.Error = &v
}

func (o SuccessResponseSimulationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessResponseSimulationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *SuccessResponseSimulationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessResponseSimulationResponse := _SuccessResponseSimulationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSuccessResponseSimulationResponse)

	if err != nil {
		return err
	}

	*o = SuccessResponseSimulationResponse(varSuccessResponseSimulationResponse)

	return err
}

type NullableSuccessResponseSimulationResponse struct {
	value *SuccessResponseSimulationResponse
	isSet bool
}

func (v NullableSuccessResponseSimulationResponse) Get() *SuccessResponseSimulationResponse {
	return v.value
}

func (v *NullableSuccessResponseSimulationResponse) Set(val *SuccessResponseSimulationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessResponseSimulationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessResponseSimulationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessResponseSimulationResponse(val *SuccessResponseSimulationResponse) *NullableSuccessResponseSimulationResponse {
	return &NullableSuccessResponseSimulationResponse{value: val, isSet: true}
}

func (v NullableSuccessResponseSimulationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessResponseSimulationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


