/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"fmt"
)

// checks if the SuccessResponsePermissionOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessResponsePermissionOut{}

// SuccessResponsePermissionOut struct for SuccessResponsePermissionOut
type SuccessResponsePermissionOut struct {
	Data PermissionOut `json:"data"`
	Meta *MetaBody `json:"meta,omitempty"`
	Error *interface{} `json:"error,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SuccessResponsePermissionOut SuccessResponsePermissionOut

// NewSuccessResponsePermissionOut instantiates a new SuccessResponsePermissionOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessResponsePermissionOut(data PermissionOut) *SuccessResponsePermissionOut {
	this := SuccessResponsePermissionOut{}
	this.Data = data
	return &this
}

// NewSuccessResponsePermissionOutWithDefaults instantiates a new SuccessResponsePermissionOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessResponsePermissionOutWithDefaults() *SuccessResponsePermissionOut {
	this := SuccessResponsePermissionOut{}
	return &this
}

// GetData returns the Data field value
func (o *SuccessResponsePermissionOut) GetData() PermissionOut {
	if o == nil {
		var ret PermissionOut
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SuccessResponsePermissionOut) GetDataOk() (*PermissionOut, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SuccessResponsePermissionOut) SetData(v PermissionOut) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SuccessResponsePermissionOut) GetMeta() MetaBody {
	if o == nil || IsNil(o.Meta) {
		var ret MetaBody
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponsePermissionOut) GetMetaOk() (*MetaBody, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SuccessResponsePermissionOut) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaBody and assigns it to the Meta field.
func (o *SuccessResponsePermissionOut) SetMeta(v MetaBody) {
	o.Meta = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SuccessResponsePermissionOut) GetError() interface{} {
	if o == nil || IsNil(o.Error) {
		var ret interface{}
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponsePermissionOut) GetErrorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SuccessResponsePermissionOut) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given interface{} and assigns it to the Error field.
func (o *SuccessResponsePermissionOut) SetError(v interface{}) {
	o.Error = &v
}

func (o SuccessResponsePermissionOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessResponsePermissionOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SuccessResponsePermissionOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessResponsePermissionOut := _SuccessResponsePermissionOut{}

	err = json.Unmarshal(data, &varSuccessResponsePermissionOut)

	if err != nil {
		return err
	}

	*o = SuccessResponsePermissionOut(varSuccessResponsePermissionOut)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "meta")
		delete(additionalProperties, "error")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSuccessResponsePermissionOut struct {
	value *SuccessResponsePermissionOut
	isSet bool
}

func (v NullableSuccessResponsePermissionOut) Get() *SuccessResponsePermissionOut {
	return v.value
}

func (v *NullableSuccessResponsePermissionOut) Set(val *SuccessResponsePermissionOut) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessResponsePermissionOut) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessResponsePermissionOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessResponsePermissionOut(val *SuccessResponsePermissionOut) *NullableSuccessResponsePermissionOut {
	return &NullableSuccessResponsePermissionOut{value: val, isSet: true}
}

func (v NullableSuccessResponsePermissionOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessResponsePermissionOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


