/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RelationshipOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RelationshipOut{}

// RelationshipOut struct for RelationshipOut
type RelationshipOut struct {
	SubjectType string `json:"subject_type"`
	SubjectId string `json:"subject_id"`
	Relation string `json:"relation"`
	ObjectType string `json:"object_type"`
	ObjectId string `json:"object_id"`
	Id int32 `json:"id"`
}

type _RelationshipOut RelationshipOut

// NewRelationshipOut instantiates a new RelationshipOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationshipOut(subjectType string, subjectId string, relation string, objectType string, objectId string, id int32) *RelationshipOut {
	this := RelationshipOut{}
	this.SubjectType = subjectType
	this.SubjectId = subjectId
	this.Relation = relation
	this.ObjectType = objectType
	this.ObjectId = objectId
	this.Id = id
	return &this
}

// NewRelationshipOutWithDefaults instantiates a new RelationshipOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationshipOutWithDefaults() *RelationshipOut {
	this := RelationshipOut{}
	return &this
}

// GetSubjectType returns the SubjectType field value
func (o *RelationshipOut) GetSubjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectType
}

// GetSubjectTypeOk returns a tuple with the SubjectType field value
// and a boolean to check if the value has been set.
func (o *RelationshipOut) GetSubjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectType, true
}

// SetSubjectType sets field value
func (o *RelationshipOut) SetSubjectType(v string) {
	o.SubjectType = v
}

// GetSubjectId returns the SubjectId field value
func (o *RelationshipOut) GetSubjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectId
}

// GetSubjectIdOk returns a tuple with the SubjectId field value
// and a boolean to check if the value has been set.
func (o *RelationshipOut) GetSubjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectId, true
}

// SetSubjectId sets field value
func (o *RelationshipOut) SetSubjectId(v string) {
	o.SubjectId = v
}

// GetRelation returns the Relation field value
func (o *RelationshipOut) GetRelation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Relation
}

// GetRelationOk returns a tuple with the Relation field value
// and a boolean to check if the value has been set.
func (o *RelationshipOut) GetRelationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relation, true
}

// SetRelation sets field value
func (o *RelationshipOut) SetRelation(v string) {
	o.Relation = v
}

// GetObjectType returns the ObjectType field value
func (o *RelationshipOut) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *RelationshipOut) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *RelationshipOut) SetObjectType(v string) {
	o.ObjectType = v
}

// GetObjectId returns the ObjectId field value
func (o *RelationshipOut) GetObjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectId
}

// GetObjectIdOk returns a tuple with the ObjectId field value
// and a boolean to check if the value has been set.
func (o *RelationshipOut) GetObjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectId, true
}

// SetObjectId sets field value
func (o *RelationshipOut) SetObjectId(v string) {
	o.ObjectId = v
}

// GetId returns the Id field value
func (o *RelationshipOut) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RelationshipOut) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RelationshipOut) SetId(v int32) {
	o.Id = v
}

func (o RelationshipOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RelationshipOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subject_type"] = o.SubjectType
	toSerialize["subject_id"] = o.SubjectId
	toSerialize["relation"] = o.Relation
	toSerialize["object_type"] = o.ObjectType
	toSerialize["object_id"] = o.ObjectId
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *RelationshipOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subject_type",
		"subject_id",
		"relation",
		"object_type",
		"object_id",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRelationshipOut := _RelationshipOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRelationshipOut)

	if err != nil {
		return err
	}

	*o = RelationshipOut(varRelationshipOut)

	return err
}

type NullableRelationshipOut struct {
	value *RelationshipOut
	isSet bool
}

func (v NullableRelationshipOut) Get() *RelationshipOut {
	return v.value
}

func (v *NullableRelationshipOut) Set(val *RelationshipOut) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationshipOut) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationshipOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationshipOut(val *RelationshipOut) *NullableRelationshipOut {
	return &NullableRelationshipOut{value: val, isSet: true}
}

func (v NullableRelationshipOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationshipOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


