/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
)

// checks if the PlaygroundInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaygroundInput{}

// PlaygroundInput struct for PlaygroundInput
type PlaygroundInput struct {
	User map[string]interface{} `json:"user,omitempty"`
	Resource map[string]interface{} `json:"resource,omitempty"`
	Action *string `json:"action,omitempty"`
	Context map[string]interface{} `json:"context,omitempty"`
}

// NewPlaygroundInput instantiates a new PlaygroundInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaygroundInput() *PlaygroundInput {
	this := PlaygroundInput{}
	var action string = ""
	this.Action = &action
	return &this
}

// NewPlaygroundInputWithDefaults instantiates a new PlaygroundInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaygroundInputWithDefaults() *PlaygroundInput {
	this := PlaygroundInput{}
	var action string = ""
	this.Action = &action
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *PlaygroundInput) GetUser() map[string]interface{} {
	if o == nil || IsNil(o.User) {
		var ret map[string]interface{}
		return ret
	}
	return o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaygroundInput) GetUserOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.User) {
		return map[string]interface{}{}, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *PlaygroundInput) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given map[string]interface{} and assigns it to the User field.
func (o *PlaygroundInput) SetUser(v map[string]interface{}) {
	o.User = v
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *PlaygroundInput) GetResource() map[string]interface{} {
	if o == nil || IsNil(o.Resource) {
		var ret map[string]interface{}
		return ret
	}
	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaygroundInput) GetResourceOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Resource) {
		return map[string]interface{}{}, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *PlaygroundInput) HasResource() bool {
	if o != nil && !IsNil(o.Resource) {
		return true
	}

	return false
}

// SetResource gets a reference to the given map[string]interface{} and assigns it to the Resource field.
func (o *PlaygroundInput) SetResource(v map[string]interface{}) {
	o.Resource = v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *PlaygroundInput) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaygroundInput) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *PlaygroundInput) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *PlaygroundInput) SetAction(v string) {
	o.Action = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *PlaygroundInput) GetContext() map[string]interface{} {
	if o == nil || IsNil(o.Context) {
		var ret map[string]interface{}
		return ret
	}
	return o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaygroundInput) GetContextOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Context) {
		return map[string]interface{}{}, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *PlaygroundInput) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given map[string]interface{} and assigns it to the Context field.
func (o *PlaygroundInput) SetContext(v map[string]interface{}) {
	o.Context = v
}

func (o PlaygroundInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaygroundInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Resource) {
		toSerialize["resource"] = o.Resource
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	return toSerialize, nil
}

type NullablePlaygroundInput struct {
	value *PlaygroundInput
	isSet bool
}

func (v NullablePlaygroundInput) Get() *PlaygroundInput {
	return v.value
}

func (v *NullablePlaygroundInput) Set(val *PlaygroundInput) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaygroundInput) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaygroundInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaygroundInput(val *PlaygroundInput) *NullablePlaygroundInput {
	return &NullablePlaygroundInput{value: val, isSet: true}
}

func (v NullablePlaygroundInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaygroundInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


