/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SuccessResponseListDictStrStr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessResponseListDictStrStr{}

// SuccessResponseListDictStrStr struct for SuccessResponseListDictStrStr
type SuccessResponseListDictStrStr struct {
	Data []map[string]string `json:"data"`
	Meta *MetaBody `json:"meta,omitempty"`
	Error *interface{} `json:"error,omitempty"`
}

type _SuccessResponseListDictStrStr SuccessResponseListDictStrStr

// NewSuccessResponseListDictStrStr instantiates a new SuccessResponseListDictStrStr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessResponseListDictStrStr(data []map[string]string) *SuccessResponseListDictStrStr {
	this := SuccessResponseListDictStrStr{}
	this.Data = data
	return &this
}

// NewSuccessResponseListDictStrStrWithDefaults instantiates a new SuccessResponseListDictStrStr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessResponseListDictStrStrWithDefaults() *SuccessResponseListDictStrStr {
	this := SuccessResponseListDictStrStr{}
	return &this
}

// GetData returns the Data field value
func (o *SuccessResponseListDictStrStr) GetData() []map[string]string {
	if o == nil {
		var ret []map[string]string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SuccessResponseListDictStrStr) GetDataOk() ([]map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SuccessResponseListDictStrStr) SetData(v []map[string]string) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SuccessResponseListDictStrStr) GetMeta() MetaBody {
	if o == nil || IsNil(o.Meta) {
		var ret MetaBody
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseListDictStrStr) GetMetaOk() (*MetaBody, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SuccessResponseListDictStrStr) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaBody and assigns it to the Meta field.
func (o *SuccessResponseListDictStrStr) SetMeta(v MetaBody) {
	o.Meta = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SuccessResponseListDictStrStr) GetError() interface{} {
	if o == nil || IsNil(o.Error) {
		var ret interface{}
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessResponseListDictStrStr) GetErrorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SuccessResponseListDictStrStr) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given interface{} and assigns it to the Error field.
func (o *SuccessResponseListDictStrStr) SetError(v interface{}) {
	o.Error = &v
}

func (o SuccessResponseListDictStrStr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessResponseListDictStrStr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *SuccessResponseListDictStrStr) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessResponseListDictStrStr := _SuccessResponseListDictStrStr{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSuccessResponseListDictStrStr)

	if err != nil {
		return err
	}

	*o = SuccessResponseListDictStrStr(varSuccessResponseListDictStrStr)

	return err
}

type NullableSuccessResponseListDictStrStr struct {
	value *SuccessResponseListDictStrStr
	isSet bool
}

func (v NullableSuccessResponseListDictStrStr) Get() *SuccessResponseListDictStrStr {
	return v.value
}

func (v *NullableSuccessResponseListDictStrStr) Set(val *SuccessResponseListDictStrStr) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessResponseListDictStrStr) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessResponseListDictStrStr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessResponseListDictStrStr(val *SuccessResponseListDictStrStr) *NullableSuccessResponseListDictStrStr {
	return &NullableSuccessResponseListDictStrStr{value: val, isSet: true}
}

func (v NullableSuccessResponseListDictStrStr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessResponseListDictStrStr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


