/*
KeyNetra

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package keynetra

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ACLOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ACLOut{}

// ACLOut struct for ACLOut
type ACLOut struct {
	SubjectType string `json:"subject_type"`
	SubjectId string `json:"subject_id"`
	ResourceType string `json:"resource_type"`
	ResourceId string `json:"resource_id"`
	Action string `json:"action"`
	Effect string `json:"effect"`
	Id int32 `json:"id"`
	TenantId int32 `json:"tenant_id"`
	CreatedAt NullableTime `json:"created_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ACLOut ACLOut

// NewACLOut instantiates a new ACLOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewACLOut(subjectType string, subjectId string, resourceType string, resourceId string, action string, effect string, id int32, tenantId int32) *ACLOut {
	this := ACLOut{}
	this.SubjectType = subjectType
	this.SubjectId = subjectId
	this.ResourceType = resourceType
	this.ResourceId = resourceId
	this.Action = action
	this.Effect = effect
	this.Id = id
	this.TenantId = tenantId
	return &this
}

// NewACLOutWithDefaults instantiates a new ACLOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewACLOutWithDefaults() *ACLOut {
	this := ACLOut{}
	return &this
}

// GetSubjectType returns the SubjectType field value
func (o *ACLOut) GetSubjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectType
}

// GetSubjectTypeOk returns a tuple with the SubjectType field value
// and a boolean to check if the value has been set.
func (o *ACLOut) GetSubjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectType, true
}

// SetSubjectType sets field value
func (o *ACLOut) SetSubjectType(v string) {
	o.SubjectType = v
}

// GetSubjectId returns the SubjectId field value
func (o *ACLOut) GetSubjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectId
}

// GetSubjectIdOk returns a tuple with the SubjectId field value
// and a boolean to check if the value has been set.
func (o *ACLOut) GetSubjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectId, true
}

// SetSubjectId sets field value
func (o *ACLOut) SetSubjectId(v string) {
	o.SubjectId = v
}

// GetResourceType returns the ResourceType field value
func (o *ACLOut) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *ACLOut) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *ACLOut) SetResourceType(v string) {
	o.ResourceType = v
}

// GetResourceId returns the ResourceId field value
func (o *ACLOut) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *ACLOut) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *ACLOut) SetResourceId(v string) {
	o.ResourceId = v
}

// GetAction returns the Action field value
func (o *ACLOut) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ACLOut) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ACLOut) SetAction(v string) {
	o.Action = v
}

// GetEffect returns the Effect field value
func (o *ACLOut) GetEffect() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Effect
}

// GetEffectOk returns a tuple with the Effect field value
// and a boolean to check if the value has been set.
func (o *ACLOut) GetEffectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Effect, true
}

// SetEffect sets field value
func (o *ACLOut) SetEffect(v string) {
	o.Effect = v
}

// GetId returns the Id field value
func (o *ACLOut) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ACLOut) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ACLOut) SetId(v int32) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *ACLOut) GetTenantId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *ACLOut) GetTenantIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *ACLOut) SetTenantId(v int32) {
	o.TenantId = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACLOut) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACLOut) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ACLOut) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *ACLOut) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}
// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *ACLOut) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *ACLOut) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

func (o ACLOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ACLOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subject_type"] = o.SubjectType
	toSerialize["subject_id"] = o.SubjectId
	toSerialize["resource_type"] = o.ResourceType
	toSerialize["resource_id"] = o.ResourceId
	toSerialize["action"] = o.Action
	toSerialize["effect"] = o.Effect
	toSerialize["id"] = o.Id
	toSerialize["tenant_id"] = o.TenantId
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ACLOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subject_type",
		"subject_id",
		"resource_type",
		"resource_id",
		"action",
		"effect",
		"id",
		"tenant_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varACLOut := _ACLOut{}

	err = json.Unmarshal(data, &varACLOut)

	if err != nil {
		return err
	}

	*o = ACLOut(varACLOut)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subject_type")
		delete(additionalProperties, "subject_id")
		delete(additionalProperties, "resource_type")
		delete(additionalProperties, "resource_id")
		delete(additionalProperties, "action")
		delete(additionalProperties, "effect")
		delete(additionalProperties, "id")
		delete(additionalProperties, "tenant_id")
		delete(additionalProperties, "created_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableACLOut struct {
	value *ACLOut
	isSet bool
}

func (v NullableACLOut) Get() *ACLOut {
	return v.value
}

func (v *NullableACLOut) Set(val *ACLOut) {
	v.value = val
	v.isSet = true
}

func (v NullableACLOut) IsSet() bool {
	return v.isSet
}

func (v *NullableACLOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableACLOut(val *ACLOut) *NullableACLOut {
	return &NullableACLOut{value: val, isSet: true}
}

func (v NullableACLOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableACLOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


