/*
KeyNetra

Testing ManagementAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package keynetra

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_keynetra_ManagementAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ManagementAPIService AddPermissionToRoleRolesRoleIdPermissionsPermissionIdPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var roleId int32
		var permissionId int32

		resp, httpRes, err := apiClient.ManagementAPI.AddPermissionToRoleRolesRoleIdPermissionsPermissionIdPost(context.Background(), roleId, permissionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService CreateAclEntryAclPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.CreateAclEntryAclPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService CreateAuthModelAuthModelPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.CreateAuthModelAuthModelPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService CreatePermissionPermissionsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.CreatePermissionPermissionsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService CreatePolicyFromDslPoliciesDslPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.CreatePolicyFromDslPoliciesDslPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService CreatePolicyPoliciesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.CreatePolicyPoliciesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService CreateRelationshipRelationshipsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.CreateRelationshipRelationshipsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService CreateRoleRolesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.CreateRoleRolesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService DeleteAclEntryAclAclIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var aclId int32

		resp, httpRes, err := apiClient.ManagementAPI.DeleteAclEntryAclAclIdDelete(context.Background(), aclId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService DeletePermissionPermissionsPermissionIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var permissionId int32

		resp, httpRes, err := apiClient.ManagementAPI.DeletePermissionPermissionsPermissionIdDelete(context.Background(), permissionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService DeletePolicyPoliciesPolicyKeyDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var policyKey string

		resp, httpRes, err := apiClient.ManagementAPI.DeletePolicyPoliciesPolicyKeyDelete(context.Background(), policyKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService DeleteRoleRolesRoleIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var roleId int32

		resp, httpRes, err := apiClient.ManagementAPI.DeleteRoleRolesRoleIdDelete(context.Background(), roleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService GetAuthModelAuthModelGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.GetAuthModelAuthModelGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService ImpactAnalysisImpactAnalysisPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.ImpactAnalysisImpactAnalysisPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService ListAclEntriesAclResourceTypeResourceIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceType string
		var resourceId string

		resp, httpRes, err := apiClient.ManagementAPI.ListAclEntriesAclResourceTypeResourceIdGet(context.Background(), resourceType, resourceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService ListAuditLogsAuditGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.ListAuditLogsAuditGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService ListPermissionRolesPermissionsPermissionIdRolesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var permissionId int32

		resp, httpRes, err := apiClient.ManagementAPI.ListPermissionRolesPermissionsPermissionIdRolesGet(context.Background(), permissionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService ListPermissionsPermissionsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.ListPermissionsPermissionsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService ListPoliciesPoliciesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.ListPoliciesPoliciesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService ListRelationshipsRelationshipsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.ListRelationshipsRelationshipsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService ListRolePermissionsRolesRoleIdPermissionsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var roleId int32

		resp, httpRes, err := apiClient.ManagementAPI.ListRolePermissionsRolesRoleIdPermissionsGet(context.Background(), roleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService ListRolesRolesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.ListRolesRolesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService RemovePermissionFromRoleRolesRoleIdPermissionsPermissionIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var roleId int32
		var permissionId int32

		resp, httpRes, err := apiClient.ManagementAPI.RemovePermissionFromRoleRolesRoleIdPermissionsPermissionIdDelete(context.Background(), roleId, permissionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService RollbackPolicyPoliciesPolicyKeyRollbackVersionPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var policyKey string
		var version int32

		resp, httpRes, err := apiClient.ManagementAPI.RollbackPolicyPoliciesPolicyKeyRollbackVersionPost(context.Background(), policyKey, version).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService SimulatePolicySimulatePolicyPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManagementAPI.SimulatePolicySimulatePolicyPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService UpdatePermissionPermissionsPermissionIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var permissionId int32

		resp, httpRes, err := apiClient.ManagementAPI.UpdatePermissionPermissionsPermissionIdPut(context.Background(), permissionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService UpdatePolicyPoliciesPolicyKeyPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var policyKey string

		resp, httpRes, err := apiClient.ManagementAPI.UpdatePolicyPoliciesPolicyKeyPut(context.Background(), policyKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManagementAPIService UpdateRoleRolesRoleIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var roleId int32

		resp, httpRes, err := apiClient.ManagementAPI.UpdateRoleRolesRoleIdPut(context.Background(), roleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
