//
// ACLOut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ACLOut: Codable, JSONEncodable, Hashable {

    public var subjectType: String
    public var subjectId: String
    public var resourceType: String
    public var resourceId: String
    public var action: String
    public var effect: String
    public var id: Int
    public var tenantId: Int
    public var createdAt: Date?

    public init(subjectType: String, subjectId: String, resourceType: String, resourceId: String, action: String, effect: String, id: Int, tenantId: Int, createdAt: Date? = nil) {
        self.subjectType = subjectType
        self.subjectId = subjectId
        self.resourceType = resourceType
        self.resourceId = resourceId
        self.action = action
        self.effect = effect
        self.id = id
        self.tenantId = tenantId
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subjectType = "subject_type"
        case subjectId = "subject_id"
        case resourceType = "resource_type"
        case resourceId = "resource_id"
        case action
        case effect
        case id
        case tenantId = "tenant_id"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subjectType, forKey: .subjectType)
        try container.encode(subjectId, forKey: .subjectId)
        try container.encode(resourceType, forKey: .resourceType)
        try container.encode(resourceId, forKey: .resourceId)
        try container.encode(action, forKey: .action)
        try container.encode(effect, forKey: .effect)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ACLOut: Identifiable {}
