//
// AdminLoginResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminLoginResponse: Codable, JSONEncodable, Hashable {

    public var accessToken: String
    public var tokenType: String? = "bearer"
    public var expiresIn: Int
    public var role: String? = "admin"
    public var tenantKey: String

    public init(accessToken: String, tokenType: String? = "bearer", expiresIn: Int, role: String? = "admin", tenantKey: String) {
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresIn = expiresIn
        self.role = role
        self.tenantKey = tenantKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresIn = "expires_in"
        case role
        case tenantKey = "tenant_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encodeIfPresent(tokenType, forKey: .tokenType)
        try container.encode(expiresIn, forKey: .expiresIn)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encode(tenantKey, forKey: .tenantKey)
    }
}

