//
// AuditRecordOut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuditRecordOut: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var principalType: String
    public var principalId: String
    public var correlationId: String?
    public var user: [String: AnyCodable]
    public var action: String
    public var resource: [String: AnyCodable]
    public var decision: String
    public var matchedPolicies: [AnyCodable]
    public var reason: String?
    public var evaluatedRules: [AnyCodable]
    public var failedConditions: [AnyCodable]
    public var createdAt: Date

    public init(id: Int, principalType: String, principalId: String, correlationId: String? = nil, user: [String: AnyCodable], action: String, resource: [String: AnyCodable], decision: String, matchedPolicies: [AnyCodable], reason: String? = nil, evaluatedRules: [AnyCodable], failedConditions: [AnyCodable], createdAt: Date) {
        self.id = id
        self.principalType = principalType
        self.principalId = principalId
        self.correlationId = correlationId
        self.user = user
        self.action = action
        self.resource = resource
        self.decision = decision
        self.matchedPolicies = matchedPolicies
        self.reason = reason
        self.evaluatedRules = evaluatedRules
        self.failedConditions = failedConditions
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case principalType = "principal_type"
        case principalId = "principal_id"
        case correlationId = "correlation_id"
        case user
        case action
        case resource
        case decision
        case matchedPolicies = "matched_policies"
        case reason
        case evaluatedRules = "evaluated_rules"
        case failedConditions = "failed_conditions"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(principalType, forKey: .principalType)
        try container.encode(principalId, forKey: .principalId)
        try container.encodeIfPresent(correlationId, forKey: .correlationId)
        try container.encode(user, forKey: .user)
        try container.encode(action, forKey: .action)
        try container.encode(resource, forKey: .resource)
        try container.encode(decision, forKey: .decision)
        try container.encode(matchedPolicies, forKey: .matchedPolicies)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encode(evaluatedRules, forKey: .evaluatedRules)
        try container.encode(failedConditions, forKey: .failedConditions)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AuditRecordOut: Identifiable {}
