//
// AuthModelCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthModelCreate: Codable, JSONEncodable, Hashable {

    public var schema: String

    public init(schema: String) {
        self.schema = schema
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schema
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(schema, forKey: .schema)
    }
}

