//
// AuthModelOut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthModelOut: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var tenantId: Int
    public var schema: String
    public var parsed: [String: AnyCodable]
    public var compiled: [String: AnyCodable]

    public init(id: Int, tenantId: Int, schema: String, parsed: [String: AnyCodable], compiled: [String: AnyCodable]) {
        self.id = id
        self.tenantId = tenantId
        self.schema = schema
        self.parsed = parsed
        self.compiled = compiled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case schema
        case parsed
        case compiled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(schema, forKey: .schema)
        try container.encode(parsed, forKey: .parsed)
        try container.encode(compiled, forKey: .compiled)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AuthModelOut: Identifiable {}
