//
// BatchAccessResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BatchAccessResponse: Codable, JSONEncodable, Hashable {

    public var results: [BatchAccessResult]
    public var revision: Int?

    public init(results: [BatchAccessResult], revision: Int? = nil) {
        self.results = results
        self.revision = revision
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results
        case revision
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(results, forKey: .results)
        try container.encodeIfPresent(revision, forKey: .revision)
    }
}

