//
// BatchAccessItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BatchAccessItem: Codable, JSONEncodable, Hashable {

    public var action: String
    public var resource: [String: AnyCodable]?

    public init(action: String, resource: [String: AnyCodable]? = nil) {
        self.action = action
        self.resource = resource
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case resource
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encodeIfPresent(resource, forKey: .resource)
    }
}

