//
// BatchAccessResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BatchAccessResult: Codable, JSONEncodable, Hashable {

    public var action: String
    public var allowed: Bool
    public var revision: Int?

    public init(action: String, allowed: Bool, revision: Int? = nil) {
        self.action = action
        self.allowed = allowed
        self.revision = revision
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case allowed
        case revision
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(allowed, forKey: .allowed)
        try container.encodeIfPresent(revision, forKey: .revision)
    }
}

