//
// ImpactAnalysisResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImpactAnalysisResponse: Codable, JSONEncodable, Hashable {

    public var gainedAccess: [Int]?
    public var lostAccess: [Int]?

    public init(gainedAccess: [Int]? = nil, lostAccess: [Int]? = nil) {
        self.gainedAccess = gainedAccess
        self.lostAccess = lostAccess
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gainedAccess = "gained_access"
        case lostAccess = "lost_access"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gainedAccess, forKey: .gainedAccess)
        try container.encodeIfPresent(lostAccess, forKey: .lostAccess)
    }
}

