//
// ImpactAnalysisRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImpactAnalysisRequest: Codable, JSONEncodable, Hashable {

    public var policyChange: String

    public init(policyChange: String) {
        self.policyChange = policyChange
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case policyChange = "policy_change"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(policyChange, forKey: .policyChange)
    }
}

