//
// PlaygroundInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlaygroundInput: Codable, JSONEncodable, Hashable {

    public var user: [String: AnyCodable]?
    public var resource: [String: AnyCodable]?
    public var action: String? = ""
    public var context: [String: AnyCodable]?

    public init(user: [String: AnyCodable]? = nil, resource: [String: AnyCodable]? = nil, action: String? = "", context: [String: AnyCodable]? = nil) {
        self.user = user
        self.resource = resource
        self.action = action
        self.context = context
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case resource
        case action
        case context
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(resource, forKey: .resource)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(context, forKey: .context)
    }
}

