//
// PlaygroundEvaluateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlaygroundEvaluateRequest: Codable, JSONEncodable, Hashable {

    public var policies: [PlaygroundPolicy]
    public var input: PlaygroundInput

    public init(policies: [PlaygroundPolicy], input: PlaygroundInput) {
        self.policies = policies
        self.input = input
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case policies
        case input
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(policies, forKey: .policies)
        try container.encode(input, forKey: .input)
    }
}

