//
// PolicyOut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PolicyOut: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var action: String
    public var effect: String
    public var priority: Int
    public var state: String? = "active"
    public var conditions: [String: AnyCodable]

    public init(id: Int, action: String, effect: String, priority: Int, state: String? = "active", conditions: [String: AnyCodable]) {
        self.id = id
        self.action = action
        self.effect = effect
        self.priority = priority
        self.state = state
        self.conditions = conditions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case action
        case effect
        case priority
        case state
        case conditions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(action, forKey: .action)
        try container.encode(effect, forKey: .effect)
        try container.encode(priority, forKey: .priority)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encode(conditions, forKey: .conditions)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PolicyOut: Identifiable {}
