//
// PolicySimulationInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PolicySimulationInput: Codable, JSONEncodable, Hashable {

    public var policyChange: String?
    public var relationshipChange: [String: AnyCodable]?
    public var roleChange: [String: AnyCodable]?

    public init(policyChange: String? = nil, relationshipChange: [String: AnyCodable]? = nil, roleChange: [String: AnyCodable]? = nil) {
        self.policyChange = policyChange
        self.relationshipChange = relationshipChange
        self.roleChange = roleChange
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case policyChange = "policy_change"
        case relationshipChange = "relationship_change"
        case roleChange = "role_change"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(policyChange, forKey: .policyChange)
        try container.encodeIfPresent(relationshipChange, forKey: .relationshipChange)
        try container.encodeIfPresent(roleChange, forKey: .roleChange)
    }
}

