//
// PolicySimulationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PolicySimulationRequest: Codable, JSONEncodable, Hashable {

    public var simulate: PolicySimulationInput?
    public var request: [String: AnyCodable]?

    public init(simulate: PolicySimulationInput? = nil, request: [String: AnyCodable]? = nil) {
        self.simulate = simulate
        self.request = request
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case simulate
        case request
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(simulate, forKey: .simulate)
        try container.encodeIfPresent(request, forKey: .request)
    }
}

