//
// RelationshipCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RelationshipCreate: Codable, JSONEncodable, Hashable {

    public var subjectType: String
    public var subjectId: String
    public var relation: String
    public var objectType: String
    public var objectId: String

    public init(subjectType: String, subjectId: String, relation: String, objectType: String, objectId: String) {
        self.subjectType = subjectType
        self.subjectId = subjectId
        self.relation = relation
        self.objectType = objectType
        self.objectId = objectId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subjectType = "subject_type"
        case subjectId = "subject_id"
        case relation
        case objectType = "object_type"
        case objectId = "object_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subjectType, forKey: .subjectType)
        try container.encode(subjectId, forKey: .subjectId)
        try container.encode(relation, forKey: .relation)
        try container.encode(objectType, forKey: .objectType)
        try container.encode(objectId, forKey: .objectId)
    }
}

