//
// SuccessResponsePermissionOut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SuccessResponsePermissionOut: Codable, JSONEncodable, Hashable {

    public var data: PermissionOut
    public var meta: MetaBody?
    public var error: Null?

    public init(data: PermissionOut, meta: MetaBody? = nil, error: Null? = nil) {
        self.data = data
        self.meta = meta
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case meta
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

